/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Sat Nov 23 21:49:49 2019. */

#ifndef PB_ONNX_ONNX_PB_H_INCLUDED
#define PB_ONNX_ONNX_PB_H_INCLUDED
#include "pb.h" /* This was modified after the export to make it compile */

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _onnx_Version {
    onnx_Version__START_VERSION = 0,
    onnx_Version_IR_VERSION_2017_10_10 = 1,
    onnx_Version_IR_VERSION_2017_10_30 = 2,
    onnx_Version_IR_VERSION_2017_11_3 = 3,
    onnx_Version_IR_VERSION_2019_1_22 = 4,
    onnx_Version_IR_VERSION_2019_3_18 = 5,
    onnx_Version_IR_VERSION = 6
} onnx_Version;
#define _onnx_Version_MIN onnx_Version__START_VERSION
#define _onnx_Version_MAX onnx_Version_IR_VERSION
#define _onnx_Version_ARRAYSIZE ((onnx_Version)(onnx_Version_IR_VERSION+1))

typedef enum _onnx_AttributeProto_AttributeType {
    onnx_AttributeProto_AttributeType_UNDEFINED = 0,
    onnx_AttributeProto_AttributeType_FLOAT = 1,
    onnx_AttributeProto_AttributeType_INT = 2,
    onnx_AttributeProto_AttributeType_STRING = 3,
    onnx_AttributeProto_AttributeType_TENSOR = 4,
    onnx_AttributeProto_AttributeType_GRAPH = 5,
    onnx_AttributeProto_AttributeType_SPARSE_TENSOR = 11,
    onnx_AttributeProto_AttributeType_FLOATS = 6,
    onnx_AttributeProto_AttributeType_INTS = 7,
    onnx_AttributeProto_AttributeType_STRINGS = 8,
    onnx_AttributeProto_AttributeType_TENSORS = 9,
    onnx_AttributeProto_AttributeType_GRAPHS = 10,
    onnx_AttributeProto_AttributeType_SPARSE_TENSORS = 12
} onnx_AttributeProto_AttributeType;
#define _onnx_AttributeProto_AttributeType_MIN onnx_AttributeProto_AttributeType_UNDEFINED
#define _onnx_AttributeProto_AttributeType_MAX onnx_AttributeProto_AttributeType_SPARSE_TENSORS
#define _onnx_AttributeProto_AttributeType_ARRAYSIZE ((onnx_AttributeProto_AttributeType)(onnx_AttributeProto_AttributeType_SPARSE_TENSORS+1))

typedef enum _onnx_TensorProto_DataType {
    onnx_TensorProto_DataType_UNDEFINED = 0,
    onnx_TensorProto_DataType_FLOAT = 1,
    onnx_TensorProto_DataType_UINT8 = 2,
    onnx_TensorProto_DataType_INT8 = 3,
    onnx_TensorProto_DataType_UINT16 = 4,
    onnx_TensorProto_DataType_INT16 = 5,
    onnx_TensorProto_DataType_INT32 = 6,
    onnx_TensorProto_DataType_INT64 = 7,
    onnx_TensorProto_DataType_STRING = 8,
    onnx_TensorProto_DataType_BOOL = 9,
    onnx_TensorProto_DataType_FLOAT16 = 10,
    onnx_TensorProto_DataType_DOUBLE = 11,
    onnx_TensorProto_DataType_UINT32 = 12,
    onnx_TensorProto_DataType_UINT64 = 13,
    onnx_TensorProto_DataType_COMPLEX64 = 14,
    onnx_TensorProto_DataType_COMPLEX128 = 15,
    onnx_TensorProto_DataType_BFLOAT16 = 16
} onnx_TensorProto_DataType;
#define _onnx_TensorProto_DataType_MIN onnx_TensorProto_DataType_UNDEFINED
#define _onnx_TensorProto_DataType_MAX onnx_TensorProto_DataType_BFLOAT16
#define _onnx_TensorProto_DataType_ARRAYSIZE ((onnx_TensorProto_DataType)(onnx_TensorProto_DataType_BFLOAT16+1))

typedef enum _onnx_TensorProto_DataLocation {
    onnx_TensorProto_DataLocation_DEFAULT = 0,
    onnx_TensorProto_DataLocation_EXTERNAL = 1
} onnx_TensorProto_DataLocation;
#define _onnx_TensorProto_DataLocation_MIN onnx_TensorProto_DataLocation_DEFAULT
#define _onnx_TensorProto_DataLocation_MAX onnx_TensorProto_DataLocation_EXTERNAL
#define _onnx_TensorProto_DataLocation_ARRAYSIZE ((onnx_TensorProto_DataLocation)(onnx_TensorProto_DataLocation_EXTERNAL+1))

/* Struct definitions */
typedef struct _onnx_TensorShapeProto {
    pb_callback_t dim;
/* @@protoc_insertion_point(struct:onnx_TensorShapeProto) */
} onnx_TensorShapeProto;

typedef struct _onnx_TypeProto_Sequence {
    struct _onnx_TypeProto *elem_type;
/* @@protoc_insertion_point(struct:onnx_TypeProto_Sequence) */
} onnx_TypeProto_Sequence;

typedef struct _onnx_GraphProto {
    pb_callback_t node;
    bool has_name;
    char name[128];
    pb_callback_t initializer;
    bool has_doc_string;
    char doc_string[0];
    pb_callback_t input;
    pb_callback_t output;
    pb_callback_t value_info;
    pb_callback_t quantization_annotation;
    pb_callback_t sparse_initializer;
/* @@protoc_insertion_point(struct:onnx_GraphProto) */
} onnx_GraphProto;

typedef struct _onnx_NodeProto {
    pb_callback_t input;
    pb_callback_t output;
    bool has_name;
    char name[128];
    bool has_op_type;
    char op_type[128];
    pb_callback_t attribute;
    bool has_doc_string;
    char doc_string[0];
    bool has_domain;
    char domain[128];
/* @@protoc_insertion_point(struct:onnx_NodeProto) */
} onnx_NodeProto;

typedef struct _onnx_OperatorSetIdProto {
    bool has_domain;
    char domain[128];
    bool has_version;
    int64_t version;
/* @@protoc_insertion_point(struct:onnx_OperatorSetIdProto) */
} onnx_OperatorSetIdProto;

typedef struct _onnx_StringStringEntryProto {
    bool has_key;
    char key[128];
    bool has_value;
    char value[128];
/* @@protoc_insertion_point(struct:onnx_StringStringEntryProto) */
} onnx_StringStringEntryProto;

typedef struct _onnx_TensorAnnotation {
    bool has_tensor_name;
    char tensor_name[128];
    pb_callback_t quant_parameter_tensor_names;
/* @@protoc_insertion_point(struct:onnx_TensorAnnotation) */
} onnx_TensorAnnotation;

typedef struct _onnx_TensorProto_Segment {
    bool has_begin;
    int64_t begin;
    bool has_end;
    int64_t end;
/* @@protoc_insertion_point(struct:onnx_TensorProto_Segment) */
} onnx_TensorProto_Segment;

typedef struct _onnx_TensorShapeProto_Dimension {
    pb_size_t which_value;
    union {
        int64_t dim_value;
        char dim_param[128];
    } value;
    bool has_denotation;
    char denotation[128];
/* @@protoc_insertion_point(struct:onnx_TensorShapeProto_Dimension) */
} onnx_TensorShapeProto_Dimension;

typedef struct _onnx_TypeProto_Map {
    bool has_key_type;
    int32_t key_type;
    struct _onnx_TypeProto *value_type;
/* @@protoc_insertion_point(struct:onnx_TypeProto_Map) */
} onnx_TypeProto_Map;

typedef struct _onnx_TypeProto_Tensor {
    int32_t *elem_type;
    bool has_shape;
    onnx_TensorShapeProto shape;
/* @@protoc_insertion_point(struct:onnx_TypeProto_Tensor) */
} onnx_TypeProto_Tensor;

typedef struct _onnx_ModelProto {
    bool has_ir_version;
    int64_t ir_version;
    bool has_producer_name;
    char producer_name[128];
    bool has_producer_version;
    char producer_version[128];
    bool has_domain;
    char domain[128];
    bool has_model_version;
    int64_t model_version;
    bool has_doc_string;
    char doc_string[0];
    bool has_graph;
    onnx_GraphProto graph;
    pb_callback_t opset_import;
    pb_callback_t metadata_props;
/* @@protoc_insertion_point(struct:onnx_ModelProto) */
} onnx_ModelProto;

typedef struct _onnx_TensorProto {
    pb_callback_t dims;
    bool has_data_type;
    int32_t data_type;
    bool has_segment;
    onnx_TensorProto_Segment segment;
    pb_callback_t float_data;
    pb_callback_t int32_data;
    pb_callback_t string_data;
    pb_callback_t int64_data;
    bool has_name;
    char name[128];
    pb_callback_t raw_data;
    pb_callback_t double_data;
    pb_callback_t uint64_data;
    bool has_doc_string;
    char doc_string[0];
    pb_callback_t external_data;
    bool has_data_location;
    onnx_TensorProto_DataLocation data_location;
/* @@protoc_insertion_point(struct:onnx_TensorProto) */
} onnx_TensorProto;

typedef struct _onnx_TypeProto {
    pb_size_t which_value;
    union {
        onnx_TypeProto_Tensor tensor_type;
        onnx_TypeProto_Sequence sequence_type;
        onnx_TypeProto_Map map_type;
    } value;
    bool has_denotation;
    char denotation[128];
/* @@protoc_insertion_point(struct:onnx_TypeProto) */
} onnx_TypeProto;

typedef struct _onnx_SparseTensorProto {
    bool has_values;
    onnx_TensorProto values;
    bool has_indices;
    onnx_TensorProto indices;
    pb_callback_t dims;
/* @@protoc_insertion_point(struct:onnx_SparseTensorProto) */
} onnx_SparseTensorProto;

typedef struct _onnx_ValueInfoProto {
    bool has_name;
    char name[128];
    bool has_type;
    onnx_TypeProto type;
    bool has_doc_string;
    char doc_string[0];
/* @@protoc_insertion_point(struct:onnx_ValueInfoProto) */
} onnx_ValueInfoProto;

typedef struct _onnx_AttributeProto {
    bool has_name;
    char name[128];
    bool has_f;
    float f;
    bool has_i;
    int64_t i;
    pb_callback_t s;
    bool has_t;
    onnx_TensorProto t;
    bool has_g;
    onnx_GraphProto g;
    pb_callback_t floats;
    pb_callback_t ints;
    pb_callback_t strings;
    pb_callback_t tensors;
    pb_callback_t graphs;
    bool has_doc_string;
    char doc_string[0];
    bool has_type;
    onnx_AttributeProto_AttributeType type;
    bool has_ref_attr_name;
    char ref_attr_name[128];
    bool has_sparse_tensor;
    onnx_SparseTensorProto sparse_tensor;
    pb_callback_t sparse_tensors;
/* @@protoc_insertion_point(struct:onnx_AttributeProto) */
} onnx_AttributeProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define onnx_AttributeProto_init_default         {false, "", false, 0, false, 0, {{NULL}, NULL}, false, onnx_TensorProto_init_default, false, onnx_GraphProto_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, "", false, _onnx_AttributeProto_AttributeType_MIN, false, "", false, onnx_SparseTensorProto_init_default, {{NULL}, NULL}}
#define onnx_ValueInfoProto_init_default         {false, "", false, onnx_TypeProto_init_default, false, ""}
#define onnx_NodeProto_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, false, "", false, "", {{NULL}, NULL}, false, "", false, ""}
#define onnx_ModelProto_init_default             {false, 0, false, "", false, "", false, "", false, 0, false, "", false, onnx_GraphProto_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define onnx_StringStringEntryProto_init_default {false, "", false, ""}
#define onnx_TensorAnnotation_init_default       {false, "", {{NULL}, NULL}}
#define onnx_GraphProto_init_default             {{{NULL}, NULL}, false, "", {{NULL}, NULL}, false, "", {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define onnx_TensorProto_init_default            {{{NULL}, NULL}, false, 0, false, onnx_TensorProto_Segment_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, "", {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, "", {{NULL}, NULL}, false, _onnx_TensorProto_DataLocation_MIN}
#define onnx_TensorProto_Segment_init_default    {false, 0, false, 0}
#define onnx_SparseTensorProto_init_default      {false, onnx_TensorProto_init_default, false, onnx_TensorProto_init_default, {{NULL}, NULL}}
#define onnx_TensorShapeProto_init_default       {{{NULL}, NULL}}
#define onnx_TensorShapeProto_Dimension_init_default {0, {0}, false, ""}
#define onnx_TypeProto_init_default              {0, {onnx_TypeProto_Tensor_init_default}, false, ""}
#define onnx_TypeProto_Tensor_init_default       {NULL, false, onnx_TensorShapeProto_init_default}
#define onnx_TypeProto_Sequence_init_default     {NULL}
#define onnx_TypeProto_Map_init_default          {false, 0, NULL}
#define onnx_OperatorSetIdProto_init_default     {false, "", false, 0}
#define onnx_AttributeProto_init_zero            {false, "", false, 0, false, 0, {{NULL}, NULL}, false, onnx_TensorProto_init_zero, false, onnx_GraphProto_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, "", false, _onnx_AttributeProto_AttributeType_MIN, false, "", false, onnx_SparseTensorProto_init_zero, {{NULL}, NULL}}
#define onnx_ValueInfoProto_init_zero            {false, "", false, onnx_TypeProto_init_zero, false, ""}
#define onnx_NodeProto_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, false, "", false, "", {{NULL}, NULL}, false, "", false, ""}
#define onnx_ModelProto_init_zero                {false, 0, false, "", false, "", false, "", false, 0, false, "", false, onnx_GraphProto_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define onnx_StringStringEntryProto_init_zero    {false, "", false, ""}
#define onnx_TensorAnnotation_init_zero          {false, "", {{NULL}, NULL}}
#define onnx_GraphProto_init_zero                {{{NULL}, NULL}, false, "", {{NULL}, NULL}, false, "", {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define onnx_TensorProto_init_zero               {{{NULL}, NULL}, false, 0, false, onnx_TensorProto_Segment_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, "", {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, "", {{NULL}, NULL}, false, _onnx_TensorProto_DataLocation_MIN}
#define onnx_TensorProto_Segment_init_zero       {false, 0, false, 0}
#define onnx_SparseTensorProto_init_zero         {false, onnx_TensorProto_init_zero, false, onnx_TensorProto_init_zero, {{NULL}, NULL}}
#define onnx_TensorShapeProto_init_zero          {{{NULL}, NULL}}
#define onnx_TensorShapeProto_Dimension_init_zero {0, {0}, false, ""}
#define onnx_TypeProto_init_zero                 {0, {onnx_TypeProto_Tensor_init_zero}, false, ""}
#define onnx_TypeProto_Tensor_init_zero          {NULL, false, onnx_TensorShapeProto_init_zero}
#define onnx_TypeProto_Sequence_init_zero        {NULL}
#define onnx_TypeProto_Map_init_zero             {false, 0, NULL}
#define onnx_OperatorSetIdProto_init_zero        {false, "", false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define onnx_TensorShapeProto_dim_tag            1
#define onnx_TypeProto_Sequence_elem_type_tag    1
#define onnx_GraphProto_node_tag                 1
#define onnx_GraphProto_name_tag                 2
#define onnx_GraphProto_initializer_tag          5
#define onnx_GraphProto_sparse_initializer_tag   15
#define onnx_GraphProto_doc_string_tag           10
#define onnx_GraphProto_input_tag                11
#define onnx_GraphProto_output_tag               12
#define onnx_GraphProto_value_info_tag           13
#define onnx_GraphProto_quantization_annotation_tag 14
#define onnx_NodeProto_input_tag                 1
#define onnx_NodeProto_output_tag                2
#define onnx_NodeProto_name_tag                  3
#define onnx_NodeProto_op_type_tag               4
#define onnx_NodeProto_domain_tag                7
#define onnx_NodeProto_attribute_tag             5
#define onnx_NodeProto_doc_string_tag            6
#define onnx_OperatorSetIdProto_domain_tag       1
#define onnx_OperatorSetIdProto_version_tag      2
#define onnx_StringStringEntryProto_key_tag      1
#define onnx_StringStringEntryProto_value_tag    2
#define onnx_TensorAnnotation_tensor_name_tag    1
#define onnx_TensorAnnotation_quant_parameter_tensor_names_tag 2
#define onnx_TensorProto_Segment_begin_tag       1
#define onnx_TensorProto_Segment_end_tag         2
#define onnx_TensorShapeProto_Dimension_dim_value_tag 1
#define onnx_TensorShapeProto_Dimension_dim_param_tag 2
#define onnx_TensorShapeProto_Dimension_denotation_tag 3
#define onnx_TypeProto_Map_key_type_tag          1
#define onnx_TypeProto_Map_value_type_tag        2
#define onnx_TypeProto_Tensor_elem_type_tag      1
#define onnx_TypeProto_Tensor_shape_tag          2
#define onnx_ModelProto_ir_version_tag           1
#define onnx_ModelProto_opset_import_tag         8
#define onnx_ModelProto_producer_name_tag        2
#define onnx_ModelProto_producer_version_tag     3
#define onnx_ModelProto_domain_tag               4
#define onnx_ModelProto_model_version_tag        5
#define onnx_ModelProto_doc_string_tag           6
#define onnx_ModelProto_graph_tag                7
#define onnx_ModelProto_metadata_props_tag       14
#define onnx_TensorProto_dims_tag                1
#define onnx_TensorProto_data_type_tag           2
#define onnx_TensorProto_segment_tag             3
#define onnx_TensorProto_float_data_tag          4
#define onnx_TensorProto_int32_data_tag          5
#define onnx_TensorProto_string_data_tag         6
#define onnx_TensorProto_int64_data_tag          7
#define onnx_TensorProto_name_tag                8
#define onnx_TensorProto_doc_string_tag          12
#define onnx_TensorProto_raw_data_tag            9
#define onnx_TensorProto_external_data_tag       13
#define onnx_TensorProto_data_location_tag       14
#define onnx_TensorProto_double_data_tag         10
#define onnx_TensorProto_uint64_data_tag         11
#define onnx_TypeProto_tensor_type_tag           1
#define onnx_TypeProto_sequence_type_tag         4
#define onnx_TypeProto_map_type_tag              5
#define onnx_TypeProto_denotation_tag            6
#define onnx_SparseTensorProto_values_tag        1
#define onnx_SparseTensorProto_indices_tag       2
#define onnx_SparseTensorProto_dims_tag          3
#define onnx_ValueInfoProto_name_tag             1
#define onnx_ValueInfoProto_type_tag             2
#define onnx_ValueInfoProto_doc_string_tag       3
#define onnx_AttributeProto_name_tag             1
#define onnx_AttributeProto_ref_attr_name_tag    21
#define onnx_AttributeProto_doc_string_tag       13
#define onnx_AttributeProto_type_tag             20
#define onnx_AttributeProto_f_tag                2
#define onnx_AttributeProto_i_tag                3
#define onnx_AttributeProto_s_tag                4
#define onnx_AttributeProto_t_tag                5
#define onnx_AttributeProto_g_tag                6
#define onnx_AttributeProto_sparse_tensor_tag    22
#define onnx_AttributeProto_floats_tag           7
#define onnx_AttributeProto_ints_tag             8
#define onnx_AttributeProto_strings_tag          9
#define onnx_AttributeProto_tensors_tag          10
#define onnx_AttributeProto_graphs_tag           11
#define onnx_AttributeProto_sparse_tensors_tag   23

/* Struct field encoding specification for nanopb */
extern const pb_field_t onnx_AttributeProto_fields[17];
extern const pb_field_t onnx_ValueInfoProto_fields[4];
extern const pb_field_t onnx_NodeProto_fields[8];
extern const pb_field_t onnx_ModelProto_fields[10];
extern const pb_field_t onnx_StringStringEntryProto_fields[3];
extern const pb_field_t onnx_TensorAnnotation_fields[3];
extern const pb_field_t onnx_GraphProto_fields[10];
extern const pb_field_t onnx_TensorProto_fields[15];
extern const pb_field_t onnx_TensorProto_Segment_fields[3];
extern const pb_field_t onnx_SparseTensorProto_fields[4];
extern const pb_field_t onnx_TensorShapeProto_fields[2];
extern const pb_field_t onnx_TensorShapeProto_Dimension_fields[4];
extern const pb_field_t onnx_TypeProto_fields[5];
extern const pb_field_t onnx_TypeProto_Tensor_fields[3];
extern const pb_field_t onnx_TypeProto_Sequence_fields[2];
extern const pb_field_t onnx_TypeProto_Map_fields[3];
extern const pb_field_t onnx_OperatorSetIdProto_fields[3];

/* Maximum encoded size of messages (where known) */
/* onnx_AttributeProto_size depends on runtime parameters */
/* onnx_ValueInfoProto_size depends on runtime parameters */
/* onnx_NodeProto_size depends on runtime parameters */
/* onnx_ModelProto_size depends on runtime parameters */
#define onnx_StringStringEntryProto_size         262
/* onnx_TensorAnnotation_size depends on runtime parameters */
/* onnx_GraphProto_size depends on runtime parameters */
/* onnx_TensorProto_size depends on runtime parameters */
#define onnx_TensorProto_Segment_size            22
/* onnx_SparseTensorProto_size depends on runtime parameters */
/* onnx_TensorShapeProto_size depends on runtime parameters */
#define onnx_TensorShapeProto_Dimension_size     262
/* onnx_TypeProto_size depends on runtime parameters */
/* onnx_TypeProto_Tensor_size depends on runtime parameters */
/* onnx_TypeProto_Sequence_size depends on runtime parameters */
/* onnx_TypeProto_Map_size depends on runtime parameters */
#define onnx_OperatorSetIdProto_size             142

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ONNX_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
