#include <CUnit/CUnit.h>
#include <CUnit/Basic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../src/pb/onnx.pb-c.h"
#include "../src/embeddedml_debug.h"
#include "test_utils.h"

#include "operators/test_onnx_backend_operators.h"
#include "models/test_model_mnist.h"
#include "models/test_model_tinyyolov2.h"
#include "models/test_model_super_resolution.h"
#include "models/common_models.h"

int main(int argc, char **argv)
{
  CU_pSuite onnxBackendSuite = NULL;
  CU_pSuite modelsTestSuite  = NULL;

  /* Initialize CUnit test registry */
  if (CUE_SUCCESS != CU_initialize_registry())
    return CU_get_error();

  /* Add onnx test (operators) suite */
  onnxBackendSuite = CU_add_suite("onnxBackendSuite",
                                   init_onnxBackendSuite,
                                   clean_onnxBackendSuite);

  /* Add models test suite*/
  modelsTestSuite = CU_add_suite("modelsTestSuite",
                                 init_Models_TestSuite,
                                 clean_Models_TestSuite);
  if (NULL == onnxBackendSuite) {
    CU_cleanup_registry();
    return CU_get_error();
  }

  if (NULL == modelsTestSuite) {
    CU_cleanup_registry();
    return CU_get_error();
  }

  /* If arguments are provided, specific test from a suite can be run */
  if (argc == 3)
  {
    printf("Run tc=%s, from suite=%s\n", argv[2], argv[1]);
  }

  /* ONNX Backent Tests */
  /* All the following test cases are part of the official onnx backend
   * tests (see docs/OnnxBackendTest.md at onnx GitHub repo)
   * If a new operator is created, just comment it and a test will run
   * for it. Note also that if the official tests change, this will need to
   * be updated
   */

  //CU_add_test(onnxBackendSuite,"test_abs",test_abs),
  //CU_add_test(onnxBackendSuite,"test_acos",test_acos),
  //CU_add_test(onnxBackendSuite,"test_acos_example",test_acos_example),
  //CU_add_test(onnxBackendSuite,"test_acosh",test_acosh),
  //CU_add_test(onnxBackendSuite,"test_acosh_example",test_acosh_example),
  CU_add_test(onnxBackendSuite,"test_add",test_add),
  CU_add_test(onnxBackendSuite,"test_add_bcast",test_add_bcast),
  //CU_add_test(onnxBackendSuite,"test_and2d",test_and2d),
  //CU_add_test(onnxBackendSuite,"test_and3d",test_and3d),
  //CU_add_test(onnxBackendSuite,"test_and4d",test_and4d),
  //CU_add_test(onnxBackendSuite,"test_and_bcast3v1d",test_and_bcast3v1d),
  //CU_add_test(onnxBackendSuite,"test_and_bcast3v2d",test_and_bcast3v2d),
  //CU_add_test(onnxBackendSuite,"test_and_bcast4v2d",test_and_bcast4v2d),
  //CU_add_test(onnxBackendSuite,"test_and_bcast4v3d",test_and_bcast4v3d),
  //CU_add_test(onnxBackendSuite,"test_and_bcast4v4d",test_and_bcast4v4d),
  //CU_add_test(onnxBackendSuite,"test_argmax_default_axis_example",test_argmax_default_axis_example),
  //CU_add_test(onnxBackendSuite,"test_argmax_default_axis_example_select_last_index",test_argmax_default_axis_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmax_default_axis_random",test_argmax_default_axis_random),
  //CU_add_test(onnxBackendSuite,"test_argmax_default_axis_random_select_last_index",test_argmax_default_axis_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmax_keepdims_example",test_argmax_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_argmax_keepdims_example_select_last_index",test_argmax_keepdims_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmax_keepdims_random",test_argmax_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_argmax_keepdims_random_select_last_index",test_argmax_keepdims_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmax_negative_axis_keepdims_example",test_argmax_negative_axis_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_argmax_negative_axis_keepdims_example_select_last_index",test_argmax_negative_axis_keepdims_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmax_negative_axis_keepdims_random",test_argmax_negative_axis_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_argmax_negative_axis_keepdims_random_select_last_index",test_argmax_negative_axis_keepdims_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmax_no_keepdims_example",test_argmax_no_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_argmax_no_keepdims_example_select_last_index",test_argmax_no_keepdims_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmax_no_keepdims_random",test_argmax_no_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_argmax_no_keepdims_random_select_last_index",test_argmax_no_keepdims_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_default_axis_example",test_argmin_default_axis_example),
  //CU_add_test(onnxBackendSuite,"test_argmin_default_axis_example_select_last_index",test_argmin_default_axis_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_default_axis_random",test_argmin_default_axis_random),
  //CU_add_test(onnxBackendSuite,"test_argmin_default_axis_random_select_last_index",test_argmin_default_axis_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_keepdims_example",test_argmin_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_argmin_keepdims_example_select_last_index",test_argmin_keepdims_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_keepdims_random",test_argmin_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_argmin_keepdims_random_select_last_index",test_argmin_keepdims_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_negative_axis_keepdims_example",test_argmin_negative_axis_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_argmin_negative_axis_keepdims_example_select_last_index",test_argmin_negative_axis_keepdims_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_negative_axis_keepdims_random",test_argmin_negative_axis_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_argmin_negative_axis_keepdims_random_select_last_index",test_argmin_negative_axis_keepdims_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_no_keepdims_example",test_argmin_no_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_argmin_no_keepdims_example_select_last_index",test_argmin_no_keepdims_example_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_argmin_no_keepdims_random",test_argmin_no_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_argmin_no_keepdims_random_select_last_index",test_argmin_no_keepdims_random_select_last_index),
  //CU_add_test(onnxBackendSuite,"test_asin",test_asin),
  //CU_add_test(onnxBackendSuite,"test_asin_example",test_asin_example),
  //CU_add_test(onnxBackendSuite,"test_asinh",test_asinh),
  //CU_add_test(onnxBackendSuite,"test_asinh_example",test_asinh_example),
  //CU_add_test(onnxBackendSuite,"test_atan",test_atan),
  //CU_add_test(onnxBackendSuite,"test_atan_example",test_atan_example),
  //CU_add_test(onnxBackendSuite,"test_atanh",test_atanh),
  //CU_add_test(onnxBackendSuite,"test_atanh_example",test_atanh_example),
  //CU_add_test(onnxBackendSuite,"test_averagepool_1d_default",test_averagepool_1d_default),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_ceil",test_averagepool_2d_ceil),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_default",test_averagepool_2d_default),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_pads",test_averagepool_2d_pads),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_pads_count_include_pad",test_averagepool_2d_pads_count_include_pad),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_precomputed_pads",test_averagepool_2d_precomputed_pads),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_precomputed_pads_count_include_pad",test_averagepool_2d_precomputed_pads_count_include_pad),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_precomputed_same_upper",test_averagepool_2d_precomputed_same_upper),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_precomputed_strides",test_averagepool_2d_precomputed_strides),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_same_lower",test_averagepool_2d_same_lower),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_same_upper",test_averagepool_2d_same_upper),
  //CU_add_test(onnxBackendSuite,"test_averagepool_2d_strides",test_averagepool_2d_strides),
  //CU_add_test(onnxBackendSuite,"test_averagepool_3d_default",test_averagepool_3d_default),
  //CU_add_test(onnxBackendSuite,"test_basic_conv_with_padding",test_basic_conv_with_padding),
  //CU_add_test(onnxBackendSuite,"test_basic_conv_without_padding",test_basic_conv_without_padding),
  //CU_add_test(onnxBackendSuite,"test_basic_convinteger",test_basic_convinteger),
  CU_add_test(onnxBackendSuite,"test_batchnorm_epsilon",test_batchnorm_epsilon),
  CU_add_test(onnxBackendSuite,"test_batchnorm_example",test_batchnorm_example),
  //CU_add_test(onnxBackendSuite,"test_bitshift_left_uint16",test_bitshift_left_uint16),
  //CU_add_test(onnxBackendSuite,"test_bitshift_left_uint32",test_bitshift_left_uint32),
  //CU_add_test(onnxBackendSuite,"test_bitshift_left_uint64",test_bitshift_left_uint64),
  //CU_add_test(onnxBackendSuite,"test_bitshift_left_uint8",test_bitshift_left_uint8),
  //CU_add_test(onnxBackendSuite,"test_bitshift_right_uint16",test_bitshift_right_uint16),
  //CU_add_test(onnxBackendSuite,"test_bitshift_right_uint32",test_bitshift_right_uint32),
  //CU_add_test(onnxBackendSuite,"test_bitshift_right_uint64",test_bitshift_right_uint64),
  //CU_add_test(onnxBackendSuite,"test_bitshift_right_uint8",test_bitshift_right_uint8),
  //CU_add_test(onnxBackendSuite,"test_cast_DOUBLE_to_FLOAT",test_cast_DOUBLE_to_FLOAT),
  //CU_add_test(onnxBackendSuite,"test_cast_DOUBLE_to_FLOAT16",test_cast_DOUBLE_to_FLOAT16),
  //CU_add_test(onnxBackendSuite,"test_cast_FLOAT16_to_DOUBLE",test_cast_FLOAT16_to_DOUBLE),
  //CU_add_test(onnxBackendSuite,"test_cast_FLOAT16_to_FLOAT",test_cast_FLOAT16_to_FLOAT),
  //CU_add_test(onnxBackendSuite,"test_cast_FLOAT_to_DOUBLE",test_cast_FLOAT_to_DOUBLE),
  //CU_add_test(onnxBackendSuite,"test_cast_FLOAT_to_FLOAT16",test_cast_FLOAT_to_FLOAT16),
  //CU_add_test(onnxBackendSuite,"test_cast_FLOAT_to_STRING",test_cast_FLOAT_to_STRING),
  //CU_add_test(onnxBackendSuite,"test_cast_STRING_to_FLOAT",test_cast_STRING_to_FLOAT),
  //CU_add_test(onnxBackendSuite,"test_ceil",test_ceil),
  //CU_add_test(onnxBackendSuite,"test_ceil_example",test_ceil_example),
  //CU_add_test(onnxBackendSuite,"test_clip",test_clip),
  //CU_add_test(onnxBackendSuite,"test_clip_default_inbounds",test_clip_default_inbounds),
  //CU_add_test(onnxBackendSuite,"test_clip_default_max",test_clip_default_max),
  //CU_add_test(onnxBackendSuite,"test_clip_default_min",test_clip_default_min),
  //CU_add_test(onnxBackendSuite,"test_clip_example",test_clip_example),
  //CU_add_test(onnxBackendSuite,"test_clip_inbounds",test_clip_inbounds),
  //CU_add_test(onnxBackendSuite,"test_clip_outbounds",test_clip_outbounds),
  //CU_add_test(onnxBackendSuite,"test_clip_splitbounds",test_clip_splitbounds),
  //CU_add_test(onnxBackendSuite,"test_compress_0",test_compress_0),
  //CU_add_test(onnxBackendSuite,"test_compress_1",test_compress_1),
  //CU_add_test(onnxBackendSuite,"test_compress_default_axis",test_compress_default_axis),
  //CU_add_test(onnxBackendSuite,"test_compress_negative_axis",test_compress_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_concat_1d_axis_0",test_concat_1d_axis_0),
  //CU_add_test(onnxBackendSuite,"test_concat_1d_axis_negative_1",test_concat_1d_axis_negative_1),
  //CU_add_test(onnxBackendSuite,"test_concat_2d_axis_0",test_concat_2d_axis_0),
  //CU_add_test(onnxBackendSuite,"test_concat_2d_axis_1",test_concat_2d_axis_1),
  //CU_add_test(onnxBackendSuite,"test_concat_2d_axis_negative_1",test_concat_2d_axis_negative_1),
  //CU_add_test(onnxBackendSuite,"test_concat_2d_axis_negative_2",test_concat_2d_axis_negative_2),
  //CU_add_test(onnxBackendSuite,"test_concat_3d_axis_0",test_concat_3d_axis_0),
  //CU_add_test(onnxBackendSuite,"test_concat_3d_axis_1",test_concat_3d_axis_1),
  //CU_add_test(onnxBackendSuite,"test_concat_3d_axis_2",test_concat_3d_axis_2),
  //CU_add_test(onnxBackendSuite,"test_concat_3d_axis_negative_1",test_concat_3d_axis_negative_1),
  //CU_add_test(onnxBackendSuite,"test_concat_3d_axis_negative_2",test_concat_3d_axis_negative_2),
  //CU_add_test(onnxBackendSuite,"test_concat_3d_axis_negative_3",test_concat_3d_axis_negative_3),
  //CU_add_test(onnxBackendSuite,"test_constant",test_constant),
  //CU_add_test(onnxBackendSuite,"test_constant_pad",test_constant_pad),
  //CU_add_test(onnxBackendSuite,"test_constantofshape_float_ones",test_constantofshape_float_ones),
  //CU_add_test(onnxBackendSuite,"test_constantofshape_int_zeros",test_constantofshape_int_zeros),
  //CU_add_test(onnxBackendSuite,"test_conv_with_strides_and_asymmetric_padding",test_conv_with_strides_and_asymmetric_padding),
  CU_add_test(onnxBackendSuite,"test_conv_with_strides_no_padding",test_conv_with_strides_no_padding),
  //CU_add_test(onnxBackendSuite,"test_conv_with_strides_padding",test_conv_with_strides_padding),
  //CU_add_test(onnxBackendSuite,"test_convinteger_with_padding",test_convinteger_with_padding),
  //CU_add_test(onnxBackendSuite,"test_convtranspose",test_convtranspose),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_1d",test_convtranspose_1d),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_3d",test_convtranspose_3d),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_dilations",test_convtranspose_dilations),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_kernel_shape",test_convtranspose_kernel_shape),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_output_shape",test_convtranspose_output_shape),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_pad",test_convtranspose_pad),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_pads",test_convtranspose_pads),
  //CU_add_test(onnxBackendSuite,"test_convtranspose_with_kernel",test_convtranspose_with_kernel),
  //CU_add_test(onnxBackendSuite,"test_cos",test_cos),
  //CU_add_test(onnxBackendSuite,"test_cos_example",test_cos_example),
  //CU_add_test(onnxBackendSuite,"test_cosh",test_cosh),
  //CU_add_test(onnxBackendSuite,"test_cosh_example",test_cosh_example),
  //CU_add_test(onnxBackendSuite,"test_cumsum_1d",test_cumsum_1d),
  //CU_add_test(onnxBackendSuite,"test_cumsum_1d_exclusive",test_cumsum_1d_exclusive),
  //CU_add_test(onnxBackendSuite,"test_cumsum_1d_reverse",test_cumsum_1d_reverse),
  //CU_add_test(onnxBackendSuite,"test_cumsum_1d_reverse_exclusive",test_cumsum_1d_reverse_exclusive),
  //CU_add_test(onnxBackendSuite,"test_cumsum_2d_axis_0",test_cumsum_2d_axis_0),
  //CU_add_test(onnxBackendSuite,"test_cumsum_2d_axis_1",test_cumsum_2d_axis_1),
  //CU_add_test(onnxBackendSuite,"test_cumsum_2d_negative_axis",test_cumsum_2d_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_depthtospace_crd_mode",test_depthtospace_crd_mode),
  //CU_add_test(onnxBackendSuite,"test_depthtospace_crd_mode_example",test_depthtospace_crd_mode_example),
  //CU_add_test(onnxBackendSuite,"test_depthtospace_dcr_mode",test_depthtospace_dcr_mode),
  //CU_add_test(onnxBackendSuite,"test_depthtospace_example",test_depthtospace_example),
  //CU_add_test(onnxBackendSuite,"test_dequantizelinear",test_dequantizelinear),
  //CU_add_test(onnxBackendSuite,"test_det_2d",test_det_2d),
  //CU_add_test(onnxBackendSuite,"test_det_nd",test_det_nd),
  //CU_add_test(onnxBackendSuite,"test_div",test_div),
  //CU_add_test(onnxBackendSuite,"test_div_bcast",test_div_bcast),
  //CU_add_test(onnxBackendSuite,"test_div_example",test_div_example),
  //CU_add_test(onnxBackendSuite,"test_dropout_default",test_dropout_default),
  //CU_add_test(onnxBackendSuite,"test_dropout_random",test_dropout_random),
  //CU_add_test(onnxBackendSuite,"test_dynamicquantizelinear",test_dynamicquantizelinear),
  //CU_add_test(onnxBackendSuite,"test_dynamicquantizelinear_expanded",test_dynamicquantizelinear_expanded),
  //CU_add_test(onnxBackendSuite,"test_dynamicquantizelinear_max_adjusted",test_dynamicquantizelinear_max_adjusted),
  //CU_add_test(onnxBackendSuite,"test_dynamicquantizelinear_max_adjusted_expanded",test_dynamicquantizelinear_max_adjusted_expanded),
  //CU_add_test(onnxBackendSuite,"test_dynamicquantizelinear_min_adjusted",test_dynamicquantizelinear_min_adjusted),
  //CU_add_test(onnxBackendSuite,"test_dynamicquantizelinear_min_adjusted_expanded",test_dynamicquantizelinear_min_adjusted_expanded),
  //CU_add_test(onnxBackendSuite,"test_edge_pad",test_edge_pad),
  //CU_add_test(onnxBackendSuite,"test_elu",test_elu),
  //CU_add_test(onnxBackendSuite,"test_elu_default",test_elu_default),
  //CU_add_test(onnxBackendSuite,"test_elu_example",test_elu_example),
  //CU_add_test(onnxBackendSuite,"test_equal",test_equal),
  //CU_add_test(onnxBackendSuite,"test_equal_bcast",test_equal_bcast),
  //CU_add_test(onnxBackendSuite,"test_erf",test_erf),
  //CU_add_test(onnxBackendSuite,"test_exp",test_exp),
  //CU_add_test(onnxBackendSuite,"test_exp_example",test_exp_example),
  //CU_add_test(onnxBackendSuite,"test_expand_dim_changed",test_expand_dim_changed),
  //CU_add_test(onnxBackendSuite,"test_expand_dim_unchanged",test_expand_dim_unchanged),
  //CU_add_test(onnxBackendSuite,"test_eyelike_populate_off_main_diagonal",test_eyelike_populate_off_main_diagonal),
  //CU_add_test(onnxBackendSuite,"test_eyelike_with_dtype",test_eyelike_with_dtype),
  //CU_add_test(onnxBackendSuite,"test_eyelike_without_dtype",test_eyelike_without_dtype),
  //CU_add_test(onnxBackendSuite,"test_flatten_axis0",test_flatten_axis0),
  //CU_add_test(onnxBackendSuite,"test_flatten_axis1",test_flatten_axis1),
  //CU_add_test(onnxBackendSuite,"test_flatten_axis2",test_flatten_axis2),
  //CU_add_test(onnxBackendSuite,"test_flatten_axis3",test_flatten_axis3),
  //CU_add_test(onnxBackendSuite,"test_flatten_default_axis",test_flatten_default_axis),
  //CU_add_test(onnxBackendSuite,"test_flatten_negative_axis1",test_flatten_negative_axis1),
  //CU_add_test(onnxBackendSuite,"test_flatten_negative_axis2",test_flatten_negative_axis2),
  //CU_add_test(onnxBackendSuite,"test_flatten_negative_axis3",test_flatten_negative_axis3),
  //CU_add_test(onnxBackendSuite,"test_flatten_negative_axis4",test_flatten_negative_axis4),
  //CU_add_test(onnxBackendSuite,"test_floor",test_floor),
  //CU_add_test(onnxBackendSuite,"test_floor_example",test_floor_example),
  //CU_add_test(onnxBackendSuite,"test_gather_0",test_gather_0),
  //CU_add_test(onnxBackendSuite,"test_gather_1",test_gather_1),
  //CU_add_test(onnxBackendSuite,"test_gather_elements_0",test_gather_elements_0),
  //CU_add_test(onnxBackendSuite,"test_gather_elements_1",test_gather_elements_1),
  //CU_add_test(onnxBackendSuite,"test_gather_elements_negative_indices",test_gather_elements_negative_indices),
  //CU_add_test(onnxBackendSuite,"test_gather_negative_indices",test_gather_negative_indices),
  //CU_add_test(onnxBackendSuite,"test_gathernd_example_float32",test_gathernd_example_float32),
  //CU_add_test(onnxBackendSuite,"test_gathernd_example_int32",test_gathernd_example_int32),
  //CU_add_test(onnxBackendSuite,"test_gemm_all_attributes",test_gemm_all_attributes),
  //CU_add_test(onnxBackendSuite,"test_gemm_alpha",test_gemm_alpha),
  //CU_add_test(onnxBackendSuite,"test_gemm_beta",test_gemm_beta),
  //CU_add_test(onnxBackendSuite,"test_gemm_default_matrix_bias",test_gemm_default_matrix_bias),
  //CU_add_test(onnxBackendSuite,"test_gemm_default_no_bias",test_gemm_default_no_bias),
  //CU_add_test(onnxBackendSuite,"test_gemm_default_scalar_bias",test_gemm_default_scalar_bias),
  //CU_add_test(onnxBackendSuite,"test_gemm_default_single_elem_vector_bias",test_gemm_default_single_elem_vector_bias),
  //CU_add_test(onnxBackendSuite,"test_gemm_default_vector_bias",test_gemm_default_vector_bias),
  //CU_add_test(onnxBackendSuite,"test_gemm_default_zero_bias",test_gemm_default_zero_bias),
  //CU_add_test(onnxBackendSuite,"test_gemm_transposeA",test_gemm_transposeA),
  //CU_add_test(onnxBackendSuite,"test_gemm_transposeB",test_gemm_transposeB),
  //CU_add_test(onnxBackendSuite,"test_globalaveragepool",test_globalaveragepool),
  //CU_add_test(onnxBackendSuite,"test_globalaveragepool_precomputed",test_globalaveragepool_precomputed),
  //CU_add_test(onnxBackendSuite,"test_globalmaxpool",test_globalmaxpool),
  //CU_add_test(onnxBackendSuite,"test_globalmaxpool_precomputed",test_globalmaxpool_precomputed),
  //CU_add_test(onnxBackendSuite,"test_greater",test_greater),
  //CU_add_test(onnxBackendSuite,"test_greater_bcast",test_greater_bcast),
  //CU_add_test(onnxBackendSuite,"test_gru_defaults",test_gru_defaults),
  //CU_add_test(onnxBackendSuite,"test_gru_seq_length",test_gru_seq_length),
  //CU_add_test(onnxBackendSuite,"test_gru_with_initial_bias",test_gru_with_initial_bias),
  //CU_add_test(onnxBackendSuite,"test_hardmax_axis_0",test_hardmax_axis_0),
  //CU_add_test(onnxBackendSuite,"test_hardmax_axis_1",test_hardmax_axis_1),
  //CU_add_test(onnxBackendSuite,"test_hardmax_axis_2",test_hardmax_axis_2),
  //CU_add_test(onnxBackendSuite,"test_hardmax_default_axis",test_hardmax_default_axis),
  //CU_add_test(onnxBackendSuite,"test_hardmax_example",test_hardmax_example),
  //CU_add_test(onnxBackendSuite,"test_hardmax_negative_axis",test_hardmax_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_hardmax_one_hot",test_hardmax_one_hot),
  //CU_add_test(onnxBackendSuite,"test_hardsigmoid",test_hardsigmoid),
  //CU_add_test(onnxBackendSuite,"test_hardsigmoid_default",test_hardsigmoid_default),
  //CU_add_test(onnxBackendSuite,"test_hardsigmoid_example",test_hardsigmoid_example),
  //CU_add_test(onnxBackendSuite,"test_identity",test_identity),
  //CU_add_test(onnxBackendSuite,"test_instancenorm_epsilon",test_instancenorm_epsilon),
  //CU_add_test(onnxBackendSuite,"test_instancenorm_example",test_instancenorm_example),
  //CU_add_test(onnxBackendSuite,"test_isinf",test_isinf),
  //CU_add_test(onnxBackendSuite,"test_isinf_negative",test_isinf_negative),
  //CU_add_test(onnxBackendSuite,"test_isinf_positive",test_isinf_positive),
  //CU_add_test(onnxBackendSuite,"test_isnan",test_isnan),
  CU_add_test(onnxBackendSuite,"test_leakyrelu",test_leakyrelu),
  CU_add_test(onnxBackendSuite,"test_leakyrelu_default",test_leakyrelu_default),
  CU_add_test(onnxBackendSuite,"test_leakyrelu_example",test_leakyrelu_example),
  //CU_add_test(onnxBackendSuite,"test_less",test_less),
  //CU_add_test(onnxBackendSuite,"test_less_bcast",test_less_bcast),
  //CU_add_test(onnxBackendSuite,"test_log",test_log),
  //CU_add_test(onnxBackendSuite,"test_log_example",test_log_example),
  //CU_add_test(onnxBackendSuite,"test_logsoftmax_axis_0",test_logsoftmax_axis_0),
  //CU_add_test(onnxBackendSuite,"test_logsoftmax_axis_1",test_logsoftmax_axis_1),
  //CU_add_test(onnxBackendSuite,"test_logsoftmax_axis_2",test_logsoftmax_axis_2),
  //CU_add_test(onnxBackendSuite,"test_logsoftmax_default_axis",test_logsoftmax_default_axis),
  //CU_add_test(onnxBackendSuite,"test_logsoftmax_example_1",test_logsoftmax_example_1),
  //CU_add_test(onnxBackendSuite,"test_logsoftmax_large_number",test_logsoftmax_large_number),
  //CU_add_test(onnxBackendSuite,"test_logsoftmax_negative_axis",test_logsoftmax_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_lrn",test_lrn),
  //CU_add_test(onnxBackendSuite,"test_lrn_default",test_lrn_default),
  //CU_add_test(onnxBackendSuite,"test_lstm_defaults",test_lstm_defaults),
  //CU_add_test(onnxBackendSuite,"test_lstm_with_initial_bias",test_lstm_with_initial_bias),
  //CU_add_test(onnxBackendSuite,"test_lstm_with_peepholes",test_lstm_with_peepholes),
  CU_add_test(onnxBackendSuite,"test_matmul_2d",test_matmul_2d),
  //CU_add_test(onnxBackendSuite,"test_matmul_3d",test_matmul_3d),
  //CU_add_test(onnxBackendSuite,"test_matmul_4d",test_matmul_4d),
  //CU_add_test(onnxBackendSuite,"test_matmulinteger",test_matmulinteger),
  //CU_add_test(onnxBackendSuite,"test_max_example",test_max_example),
  //CU_add_test(onnxBackendSuite,"test_max_one_input",test_max_one_input),
  //CU_add_test(onnxBackendSuite,"test_max_two_inputs",test_max_two_inputs),
  //CU_add_test(onnxBackendSuite,"test_maxpool_1d_default",test_maxpool_1d_default),
  //CU_add_test(onnxBackendSuite,"test_maxpool_2d_ceil",test_maxpool_2d_ceil),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_default",test_maxpool_2d_default),
  //CU_add_test(onnxBackendSuite,"test_maxpool_2d_dilations",test_maxpool_2d_dilations),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_pads",test_maxpool_2d_pads),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_precomputed_pads",test_maxpool_2d_precomputed_pads),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_precomputed_same_upper",test_maxpool_2d_precomputed_same_upper),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_precomputed_strides",test_maxpool_2d_precomputed_strides),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_same_lower",test_maxpool_2d_same_lower),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_same_upper",test_maxpool_2d_same_upper),
  CU_add_test(onnxBackendSuite,"test_maxpool_2d_strides",test_maxpool_2d_strides),
  //CU_add_test(onnxBackendSuite,"test_maxpool_3d_default",test_maxpool_3d_default),
  //CU_add_test(onnxBackendSuite,"test_maxpool_with_argmax_2d_precomputed_pads",test_maxpool_with_argmax_2d_precomputed_pads),
  //CU_add_test(onnxBackendSuite,"test_maxpool_with_argmax_2d_precomputed_strides",test_maxpool_with_argmax_2d_precomputed_strides),
  //CU_add_test(onnxBackendSuite,"test_maxunpool_export_with_output_shape",test_maxunpool_export_with_output_shape),
  //CU_add_test(onnxBackendSuite,"test_maxunpool_export_without_output_shape",test_maxunpool_export_without_output_shape),
  //CU_add_test(onnxBackendSuite,"test_mean_example",test_mean_example),
  //CU_add_test(onnxBackendSuite,"test_mean_one_input",test_mean_one_input),
  //CU_add_test(onnxBackendSuite,"test_mean_two_inputs",test_mean_two_inputs),
  //CU_add_test(onnxBackendSuite,"test_min_example",test_min_example),
  //CU_add_test(onnxBackendSuite,"test_min_one_input",test_min_one_input),
  //CU_add_test(onnxBackendSuite,"test_min_two_inputs",test_min_two_inputs),
  //CU_add_test(onnxBackendSuite,"test_mod_broadcast",test_mod_broadcast),
  //CU_add_test(onnxBackendSuite,"test_mod_int64_fmod",test_mod_int64_fmod),
  //CU_add_test(onnxBackendSuite,"test_mod_mixed_sign_float16",test_mod_mixed_sign_float16),
  //CU_add_test(onnxBackendSuite,"test_mod_mixed_sign_float32",test_mod_mixed_sign_float32),
  //CU_add_test(onnxBackendSuite,"test_mod_mixed_sign_float64",test_mod_mixed_sign_float64),
  //CU_add_test(onnxBackendSuite,"test_mod_mixed_sign_int16",test_mod_mixed_sign_int16),
  //CU_add_test(onnxBackendSuite,"test_mod_mixed_sign_int32",test_mod_mixed_sign_int32),
  //CU_add_test(onnxBackendSuite,"test_mod_mixed_sign_int64",test_mod_mixed_sign_int64),
  //CU_add_test(onnxBackendSuite,"test_mod_mixed_sign_int8",test_mod_mixed_sign_int8),
  //CU_add_test(onnxBackendSuite,"test_mod_uint16",test_mod_uint16),
  //CU_add_test(onnxBackendSuite,"test_mod_uint32",test_mod_uint32),
  //CU_add_test(onnxBackendSuite,"test_mod_uint64",test_mod_uint64),
  //CU_add_test(onnxBackendSuite,"test_mod_uint8",test_mod_uint8),
  //CU_add_test(onnxBackendSuite,"test_mul",test_mul),
  //CU_add_test(onnxBackendSuite,"test_mul_bcast",test_mul_bcast),
  //CU_add_test(onnxBackendSuite,"test_mul_example",test_mul_example),
  //CU_add_test(onnxBackendSuite,"test_mvn",test_mvn),
  //CU_add_test(onnxBackendSuite,"test_mvn_expanded",test_mvn_expanded),
  //CU_add_test(onnxBackendSuite,"test_neg",test_neg),
  //CU_add_test(onnxBackendSuite,"test_neg_example",test_neg_example),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_center_point_box_format",test_nonmaxsuppression_center_point_box_format),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_flipped_coordinates",test_nonmaxsuppression_flipped_coordinates),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_identical_boxes",test_nonmaxsuppression_identical_boxes),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_limit_output_size",test_nonmaxsuppression_limit_output_size),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_single_box",test_nonmaxsuppression_single_box),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_suppress_by_IOU",test_nonmaxsuppression_suppress_by_IOU),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_suppress_by_IOU_and_scores",test_nonmaxsuppression_suppress_by_IOU_and_scores),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_two_batches",test_nonmaxsuppression_two_batches),
  //CU_add_test(onnxBackendSuite,"test_nonmaxsuppression_two_classes",test_nonmaxsuppression_two_classes),
  //CU_add_test(onnxBackendSuite,"test_nonzero_example",test_nonzero_example),
  //CU_add_test(onnxBackendSuite,"test_not_2d",test_not_2d),
  //CU_add_test(onnxBackendSuite,"test_not_3d",test_not_3d),
  //CU_add_test(onnxBackendSuite,"test_not_4d",test_not_4d),
  //CU_add_test(onnxBackendSuite,"test_onehot_negative_indices",test_onehot_negative_indices),
  //CU_add_test(onnxBackendSuite,"test_onehot_with_axis",test_onehot_with_axis),
  //CU_add_test(onnxBackendSuite,"test_onehot_with_negative_axis",test_onehot_with_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_onehot_without_axis",test_onehot_without_axis),
  //CU_add_test(onnxBackendSuite,"test_or2d",test_or2d),
  //CU_add_test(onnxBackendSuite,"test_or3d",test_or3d),
  //CU_add_test(onnxBackendSuite,"test_or4d",test_or4d),
  //CU_add_test(onnxBackendSuite,"test_or_bcast3v1d",test_or_bcast3v1d),
  //CU_add_test(onnxBackendSuite,"test_or_bcast3v2d",test_or_bcast3v2d),
  //CU_add_test(onnxBackendSuite,"test_or_bcast4v2d",test_or_bcast4v2d),
  //CU_add_test(onnxBackendSuite,"test_or_bcast4v3d",test_or_bcast4v3d),
  //CU_add_test(onnxBackendSuite,"test_or_bcast4v4d",test_or_bcast4v4d),
  //CU_add_test(onnxBackendSuite,"test_pow",test_pow),
  //CU_add_test(onnxBackendSuite,"test_pow_bcast_array",test_pow_bcast_array),
  //CU_add_test(onnxBackendSuite,"test_pow_bcast_scalar",test_pow_bcast_scalar),
  //CU_add_test(onnxBackendSuite,"test_pow_example",test_pow_example),
  //CU_add_test(onnxBackendSuite,"test_prelu_broadcast",test_prelu_broadcast),
  //CU_add_test(onnxBackendSuite,"test_prelu_example",test_prelu_example),
  //CU_add_test(onnxBackendSuite,"test_qlinearconv",test_qlinearconv),
  //CU_add_test(onnxBackendSuite,"test_qlinearmatmul_2D",test_qlinearmatmul_2D),
  //CU_add_test(onnxBackendSuite,"test_qlinearmatmul_3D",test_qlinearmatmul_3D),
  //CU_add_test(onnxBackendSuite,"test_quantizelinear",test_quantizelinear),
  //CU_add_test(onnxBackendSuite,"test_range_float_type_positive_delta",test_range_float_type_positive_delta),
  //CU_add_test(onnxBackendSuite,"test_range_float_type_positive_delta_expanded",test_range_float_type_positive_delta_expanded),
  //CU_add_test(onnxBackendSuite,"test_range_int32_type_negative_delta",test_range_int32_type_negative_delta),
  //CU_add_test(onnxBackendSuite,"test_range_int32_type_negative_delta_expanded",test_range_int32_type_negative_delta_expanded),
  //CU_add_test(onnxBackendSuite,"test_reciprocal",test_reciprocal),
  //CU_add_test(onnxBackendSuite,"test_reciprocal_example",test_reciprocal_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_default_axes_keepdims_example",test_reduce_l1_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_default_axes_keepdims_random",test_reduce_l1_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_do_not_keepdims_example",test_reduce_l1_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_do_not_keepdims_random",test_reduce_l1_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_keep_dims_example",test_reduce_l1_keep_dims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_keep_dims_random",test_reduce_l1_keep_dims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_negative_axes_keep_dims_example",test_reduce_l1_negative_axes_keep_dims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l1_negative_axes_keep_dims_random",test_reduce_l1_negative_axes_keep_dims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_default_axes_keepdims_example",test_reduce_l2_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_default_axes_keepdims_random",test_reduce_l2_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_do_not_keepdims_example",test_reduce_l2_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_do_not_keepdims_random",test_reduce_l2_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_keep_dims_example",test_reduce_l2_keep_dims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_keep_dims_random",test_reduce_l2_keep_dims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_negative_axes_keep_dims_example",test_reduce_l2_negative_axes_keep_dims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_l2_negative_axes_keep_dims_random",test_reduce_l2_negative_axes_keep_dims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum",test_reduce_log_sum),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_asc_axes",test_reduce_log_sum_asc_axes),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_default",test_reduce_log_sum_default),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_desc_axes",test_reduce_log_sum_desc_axes),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_default_axes_keepdims_example",test_reduce_log_sum_exp_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_default_axes_keepdims_random",test_reduce_log_sum_exp_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_do_not_keepdims_example",test_reduce_log_sum_exp_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_do_not_keepdims_random",test_reduce_log_sum_exp_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_keepdims_example",test_reduce_log_sum_exp_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_keepdims_random",test_reduce_log_sum_exp_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_negative_axes_keepdims_example",test_reduce_log_sum_exp_negative_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_exp_negative_axes_keepdims_random",test_reduce_log_sum_exp_negative_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_log_sum_negative_axes",test_reduce_log_sum_negative_axes),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_default_axes_keepdim_example",test_reduce_max_default_axes_keepdim_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_default_axes_keepdims_random",test_reduce_max_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_do_not_keepdims_example",test_reduce_max_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_do_not_keepdims_random",test_reduce_max_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_keepdims_example",test_reduce_max_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_keepdims_random",test_reduce_max_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_negative_axes_keepdims_example",test_reduce_max_negative_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_max_negative_axes_keepdims_random",test_reduce_max_negative_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_default_axes_keepdims_example",test_reduce_mean_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_default_axes_keepdims_random",test_reduce_mean_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_do_not_keepdims_example",test_reduce_mean_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_do_not_keepdims_random",test_reduce_mean_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_keepdims_example",test_reduce_mean_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_keepdims_random",test_reduce_mean_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_negative_axes_keepdims_example",test_reduce_mean_negative_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_mean_negative_axes_keepdims_random",test_reduce_mean_negative_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_default_axes_keepdims_example",test_reduce_min_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_default_axes_keepdims_random",test_reduce_min_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_do_not_keepdims_example",test_reduce_min_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_do_not_keepdims_random",test_reduce_min_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_keepdims_example",test_reduce_min_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_keepdims_random",test_reduce_min_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_negative_axes_keepdims_example",test_reduce_min_negative_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_min_negative_axes_keepdims_random",test_reduce_min_negative_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_default_axes_keepdims_example",test_reduce_prod_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_default_axes_keepdims_random",test_reduce_prod_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_do_not_keepdims_example",test_reduce_prod_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_do_not_keepdims_random",test_reduce_prod_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_keepdims_example",test_reduce_prod_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_keepdims_random",test_reduce_prod_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_negative_axes_keepdims_example",test_reduce_prod_negative_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_prod_negative_axes_keepdims_random",test_reduce_prod_negative_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_default_axes_keepdims_example",test_reduce_sum_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_default_axes_keepdims_random",test_reduce_sum_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_do_not_keepdims_example",test_reduce_sum_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_do_not_keepdims_random",test_reduce_sum_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_keepdims_example",test_reduce_sum_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_keepdims_random",test_reduce_sum_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_negative_axes_keepdims_example",test_reduce_sum_negative_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_negative_axes_keepdims_random",test_reduce_sum_negative_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_default_axes_keepdims_example",test_reduce_sum_square_default_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_default_axes_keepdims_random",test_reduce_sum_square_default_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_do_not_keepdims_example",test_reduce_sum_square_do_not_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_do_not_keepdims_random",test_reduce_sum_square_do_not_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_keepdims_example",test_reduce_sum_square_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_keepdims_random",test_reduce_sum_square_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_negative_axes_keepdims_example",test_reduce_sum_square_negative_axes_keepdims_example),
  //CU_add_test(onnxBackendSuite,"test_reduce_sum_square_negative_axes_keepdims_random",test_reduce_sum_square_negative_axes_keepdims_random),
  //CU_add_test(onnxBackendSuite,"test_reflect_pad",test_reflect_pad),
  CU_add_test(onnxBackendSuite,"test_relu",test_relu),
  //CU_add_test(onnxBackendSuite,"test_reshape_extended_dims",test_reshape_extended_dims),
  //CU_add_test(onnxBackendSuite,"test_reshape_negative_dim",test_reshape_negative_dim),
  //CU_add_test(onnxBackendSuite,"test_reshape_negative_extended_dims",test_reshape_negative_extended_dims),
  //CU_add_test(onnxBackendSuite,"test_reshape_one_dim",test_reshape_one_dim),
  //CU_add_test(onnxBackendSuite,"test_reshape_reduced_dims",test_reshape_reduced_dims),
  //CU_add_test(onnxBackendSuite,"test_reshape_reordered_all_dims",test_reshape_reordered_all_dims),
  //CU_add_test(onnxBackendSuite,"test_reshape_reordered_last_dims",test_reshape_reordered_last_dims),
  //CU_add_test(onnxBackendSuite,"test_reshape_zero_and_negative_dim",test_reshape_zero_and_negative_dim),
  //CU_add_test(onnxBackendSuite,"test_reshape_zero_dim",test_reshape_zero_dim),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_scales_cubic",test_resize_downsample_scales_cubic),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_scales_cubic_A_n0p5_exclude_outside",test_resize_downsample_scales_cubic_A_n0p5_exclude_outside),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_scales_cubic_align_corners",test_resize_downsample_scales_cubic_align_corners),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_scales_linear",test_resize_downsample_scales_linear),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_scales_linear_align_corners",test_resize_downsample_scales_linear_align_corners),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_scales_nearest",test_resize_downsample_scales_nearest),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_sizes_cubic",test_resize_downsample_sizes_cubic),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_sizes_linear_pytorch_half_pixel",test_resize_downsample_sizes_linear_pytorch_half_pixel),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_sizes_nearest",test_resize_downsample_sizes_nearest),
  //CU_add_test(onnxBackendSuite,"test_resize_downsample_sizes_nearest_tf_half_pixel_for_nn",test_resize_downsample_sizes_nearest_tf_half_pixel_for_nn),
  //CU_add_test(onnxBackendSuite,"test_resize_tf_crop_and_resize",test_resize_tf_crop_and_resize),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_scales_cubic",test_resize_upsample_scales_cubic),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_scales_cubic_A_n0p5_exclude_outside",test_resize_upsample_scales_cubic_A_n0p5_exclude_outside),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_scales_cubic_align_corners",test_resize_upsample_scales_cubic_align_corners),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_scales_cubic_asymmetric",test_resize_upsample_scales_cubic_asymmetric),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_scales_linear",test_resize_upsample_scales_linear),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_scales_linear_align_corners",test_resize_upsample_scales_linear_align_corners),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_scales_nearest",test_resize_upsample_scales_nearest),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_sizes_cubic",test_resize_upsample_sizes_cubic),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_sizes_nearest",test_resize_upsample_sizes_nearest),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_sizes_nearest_ceil_half_pixel",test_resize_upsample_sizes_nearest_ceil_half_pixel),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_sizes_nearest_floor_align_corners",test_resize_upsample_sizes_nearest_floor_align_corners),
  //CU_add_test(onnxBackendSuite,"test_resize_upsample_sizes_nearest_round_prefer_ceil_asymmetric",test_resize_upsample_sizes_nearest_round_prefer_ceil_asymmetric),
  //CU_add_test(onnxBackendSuite,"test_reversesequence_batch",test_reversesequence_batch),
  //CU_add_test(onnxBackendSuite,"test_reversesequence_time",test_reversesequence_time),
  //CU_add_test(onnxBackendSuite,"test_rnn_seq_length",test_rnn_seq_length),
  //CU_add_test(onnxBackendSuite,"test_roialign",test_roialign),
  //CU_add_test(onnxBackendSuite,"test_round",test_round),
  //CU_add_test(onnxBackendSuite,"test_scan9_sum",test_scan9_sum),
  //CU_add_test(onnxBackendSuite,"test_scan_sum",test_scan_sum),
  //CU_add_test(onnxBackendSuite,"test_scatter_elements_with_axis",test_scatter_elements_with_axis),
  //CU_add_test(onnxBackendSuite,"test_scatter_elements_with_negative_indices",test_scatter_elements_with_negative_indices),
  //CU_add_test(onnxBackendSuite,"test_scatter_elements_without_axis",test_scatter_elements_without_axis),
  //CU_add_test(onnxBackendSuite,"test_scatter_with_axis",test_scatter_with_axis),
  //CU_add_test(onnxBackendSuite,"test_scatter_without_axis",test_scatter_without_axis),
  //CU_add_test(onnxBackendSuite,"test_scatternd",test_scatternd),
  //CU_add_test(onnxBackendSuite,"test_selu",test_selu),
  //CU_add_test(onnxBackendSuite,"test_selu_default",test_selu_default),
  //CU_add_test(onnxBackendSuite,"test_selu_example",test_selu_example),
  //CU_add_test(onnxBackendSuite,"test_shape",test_shape),
  //CU_add_test(onnxBackendSuite,"test_shape_example",test_shape_example),
  //CU_add_test(onnxBackendSuite,"test_shrink_hard",test_shrink_hard),
  //CU_add_test(onnxBackendSuite,"test_shrink_soft",test_shrink_soft),
  //CU_add_test(onnxBackendSuite,"test_sigmoid",test_sigmoid),
  //CU_add_test(onnxBackendSuite,"test_sigmoid_example",test_sigmoid_example),
  //CU_add_test(onnxBackendSuite,"test_sign",test_sign),
  //CU_add_test(onnxBackendSuite,"test_simple_rnn_defaults",test_simple_rnn_defaults),
  //CU_add_test(onnxBackendSuite,"test_simple_rnn_with_initial_bias",test_simple_rnn_with_initial_bias),
  //CU_add_test(onnxBackendSuite,"test_sin",test_sin),
  //CU_add_test(onnxBackendSuite,"test_sin_example",test_sin_example),
  //CU_add_test(onnxBackendSuite,"test_sinh",test_sinh),
  //CU_add_test(onnxBackendSuite,"test_sinh_example",test_sinh_example),
  //CU_add_test(onnxBackendSuite,"test_size",test_size),
  //CU_add_test(onnxBackendSuite,"test_size_example",test_size_example),
  //CU_add_test(onnxBackendSuite,"test_slice",test_slice),
  //CU_add_test(onnxBackendSuite,"test_slice_default_axes",test_slice_default_axes),
  //CU_add_test(onnxBackendSuite,"test_slice_default_steps",test_slice_default_steps),
  //CU_add_test(onnxBackendSuite,"test_slice_end_out_of_bounds",test_slice_end_out_of_bounds),
  //CU_add_test(onnxBackendSuite,"test_slice_neg",test_slice_neg),
  //CU_add_test(onnxBackendSuite,"test_slice_neg_steps",test_slice_neg_steps),
  //CU_add_test(onnxBackendSuite,"test_slice_negative_axes",test_slice_negative_axes),
  //CU_add_test(onnxBackendSuite,"test_slice_start_out_of_bounds",test_slice_start_out_of_bounds),
  //CU_add_test(onnxBackendSuite,"test_softmax_axis_0",test_softmax_axis_0),
  //CU_add_test(onnxBackendSuite,"test_softmax_axis_1",test_softmax_axis_1),
  //CU_add_test(onnxBackendSuite,"test_softmax_axis_2",test_softmax_axis_2),
  //CU_add_test(onnxBackendSuite,"test_softmax_default_axis",test_softmax_default_axis),
  //CU_add_test(onnxBackendSuite,"test_softmax_example",test_softmax_example),
  //CU_add_test(onnxBackendSuite,"test_softmax_large_number",test_softmax_large_number),
  //CU_add_test(onnxBackendSuite,"test_softmax_negative_axis",test_softmax_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_softplus",test_softplus),
  //CU_add_test(onnxBackendSuite,"test_softplus_example",test_softplus_example),
  //CU_add_test(onnxBackendSuite,"test_softsign",test_softsign),
  //CU_add_test(onnxBackendSuite,"test_softsign_example",test_softsign_example),
  //CU_add_test(onnxBackendSuite,"test_split_equal_parts_1d",test_split_equal_parts_1d),
  //CU_add_test(onnxBackendSuite,"test_split_equal_parts_2d",test_split_equal_parts_2d),
  //CU_add_test(onnxBackendSuite,"test_split_equal_parts_default_axis",test_split_equal_parts_default_axis),
  //CU_add_test(onnxBackendSuite,"test_split_variable_parts_1d",test_split_variable_parts_1d),
  //CU_add_test(onnxBackendSuite,"test_split_variable_parts_2d",test_split_variable_parts_2d),
  //CU_add_test(onnxBackendSuite,"test_split_variable_parts_default_axis",test_split_variable_parts_default_axis),
  //CU_add_test(onnxBackendSuite,"test_sqrt",test_sqrt),
  //CU_add_test(onnxBackendSuite,"test_sqrt_example",test_sqrt_example),
  //CU_add_test(onnxBackendSuite,"test_squeeze",test_squeeze),
  //CU_add_test(onnxBackendSuite,"test_squeeze_negative_axes",test_squeeze_negative_axes),
  //CU_add_test(onnxBackendSuite,"test_strnormalizer_export_monday_casesensintive_lower",test_strnormalizer_export_monday_casesensintive_lower),
  //CU_add_test(onnxBackendSuite,"test_strnormalizer_export_monday_casesensintive_nochangecase",test_strnormalizer_export_monday_casesensintive_nochangecase),
  //CU_add_test(onnxBackendSuite,"test_strnormalizer_export_monday_casesensintive_upper",test_strnormalizer_export_monday_casesensintive_upper),
  //CU_add_test(onnxBackendSuite,"test_strnormalizer_export_monday_empty_output",test_strnormalizer_export_monday_empty_output),
  //CU_add_test(onnxBackendSuite,"test_strnormalizer_export_monday_insensintive_upper_twodim",test_strnormalizer_export_monday_insensintive_upper_twodim),
  //CU_add_test(onnxBackendSuite,"test_strnormalizer_nostopwords_nochangecase",test_strnormalizer_nostopwords_nochangecase),
  //CU_add_test(onnxBackendSuite,"test_sub",test_sub),
  //CU_add_test(onnxBackendSuite,"test_sub_bcast",test_sub_bcast),
  //CU_add_test(onnxBackendSuite,"test_sub_example",test_sub_example),
  //CU_add_test(onnxBackendSuite,"test_sum_example",test_sum_example),
  //CU_add_test(onnxBackendSuite,"test_sum_one_input",test_sum_one_input),
  //CU_add_test(onnxBackendSuite,"test_sum_two_inputs",test_sum_two_inputs),
  //CU_add_test(onnxBackendSuite,"test_tan",test_tan),
  //CU_add_test(onnxBackendSuite,"test_tan_example",test_tan_example),
  //CU_add_test(onnxBackendSuite,"test_tanh",test_tanh),
  //CU_add_test(onnxBackendSuite,"test_tanh_example",test_tanh_example),
  //CU_add_test(onnxBackendSuite,"test_tfidfvectorizer_tf_batch_onlybigrams_skip0",test_tfidfvectorizer_tf_batch_onlybigrams_skip0),
  //CU_add_test(onnxBackendSuite,"test_tfidfvectorizer_tf_batch_onlybigrams_skip5",test_tfidfvectorizer_tf_batch_onlybigrams_skip5),
  //CU_add_test(onnxBackendSuite,"test_tfidfvectorizer_tf_batch_uniandbigrams_skip5",test_tfidfvectorizer_tf_batch_uniandbigrams_skip5),
  //CU_add_test(onnxBackendSuite,"test_tfidfvectorizer_tf_only_bigrams_skip0",test_tfidfvectorizer_tf_only_bigrams_skip0),
  //CU_add_test(onnxBackendSuite,"test_tfidfvectorizer_tf_onlybigrams_levelempty",test_tfidfvectorizer_tf_onlybigrams_levelempty),
  //CU_add_test(onnxBackendSuite,"test_tfidfvectorizer_tf_onlybigrams_skip5",test_tfidfvectorizer_tf_onlybigrams_skip5),
  //CU_add_test(onnxBackendSuite,"test_tfidfvectorizer_tf_uniandbigrams_skip5",test_tfidfvectorizer_tf_uniandbigrams_skip5),
  //CU_add_test(onnxBackendSuite,"test_thresholdedrelu",test_thresholdedrelu),
  //CU_add_test(onnxBackendSuite,"test_thresholdedrelu_default",test_thresholdedrelu_default),
  //CU_add_test(onnxBackendSuite,"test_thresholdedrelu_example",test_thresholdedrelu_example),
  //CU_add_test(onnxBackendSuite,"test_tile",test_tile),
  //CU_add_test(onnxBackendSuite,"test_tile_precomputed",test_tile_precomputed),
  //CU_add_test(onnxBackendSuite,"test_top_k",test_top_k),
  //CU_add_test(onnxBackendSuite,"test_top_k_negative_axis",test_top_k_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_top_k_smallest",test_top_k_smallest),
  //CU_add_test(onnxBackendSuite,"test_transpose_all_permutations_0",test_transpose_all_permutations_0),
  //CU_add_test(onnxBackendSuite,"test_transpose_all_permutations_1",test_transpose_all_permutations_1),
  //CU_add_test(onnxBackendSuite,"test_transpose_all_permutations_2",test_transpose_all_permutations_2),
  //CU_add_test(onnxBackendSuite,"test_transpose_all_permutations_3",test_transpose_all_permutations_3),
  //CU_add_test(onnxBackendSuite,"test_transpose_all_permutations_4",test_transpose_all_permutations_4),
  //CU_add_test(onnxBackendSuite,"test_transpose_all_permutations_5",test_transpose_all_permutations_5),
  //CU_add_test(onnxBackendSuite,"test_transpose_default",test_transpose_default),
  //CU_add_test(onnxBackendSuite,"test_unique_not_sorted_without_axis",test_unique_not_sorted_without_axis),
  //CU_add_test(onnxBackendSuite,"test_unique_sorted_with_axis",test_unique_sorted_with_axis),
  //CU_add_test(onnxBackendSuite,"test_unique_sorted_with_axis_3d",test_unique_sorted_with_axis_3d),
  //CU_add_test(onnxBackendSuite,"test_unique_sorted_with_negative_axis",test_unique_sorted_with_negative_axis),
  //CU_add_test(onnxBackendSuite,"test_unique_sorted_without_axis",test_unique_sorted_without_axis),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_axis_0",test_unsqueeze_axis_0),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_axis_1",test_unsqueeze_axis_1),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_axis_2",test_unsqueeze_axis_2),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_axis_3",test_unsqueeze_axis_3),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_negative_axes",test_unsqueeze_negative_axes),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_three_axes",test_unsqueeze_three_axes),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_two_axes",test_unsqueeze_two_axes),
  //CU_add_test(onnxBackendSuite,"test_unsqueeze_unsorted_axes",test_unsqueeze_unsorted_axes),
  //CU_add_test(onnxBackendSuite,"test_upsample_nearest",test_upsample_nearest),
  //CU_add_test(onnxBackendSuite,"test_where_example",test_where_example),
  //CU_add_test(onnxBackendSuite,"test_where_long_example",test_where_long_example),
  //CU_add_test(onnxBackendSuite,"test_xor2d",test_xor2d),
  //CU_add_test(onnxBackendSuite,"test_xor3d",test_xor3d),
  //CU_add_test(onnxBackendSuite,"test_xor4d",test_xor4d),
  //CU_add_test(onnxBackendSuite,"test_xor_bcast3v1d",test_xor_bcast3v1d),
  //CU_add_test(onnxBackendSuite,"test_xor_bcast3v2d",test_xor_bcast3v2d),
  //CU_add_test(onnxBackendSuite,"test_xor_bcast4v2d",test_xor_bcast4v2d),
  //CU_add_test(onnxBackendSuite,"test_xor_bcast4v3d",test_xor_bcast4v3d),
  //CU_add_test(onnxBackendSuite,"test_xor_bcast4v4d",test_xor_bcast4v4d),


  /* Models tests */
  /* This suite tests a whole model end to end. All data is taken
   * form ONNX repository, where the model plus a set of inputs/outputs
   * is provided */
  CU_add_test(modelsTestSuite, "test_model_mnist", test_model_mnist);
  //CU_add_test(modelsTestSuite, "test_model_mnist_per_node", test_model_mnist_per_node);
  //CU_add_test(modelsTestSuite, "test_model_tinyyolov2", test_model_tinyyolov2);
  //CU_add_test(modelsTestSuite, "test_model_super_resolution", test_model_super_resolution);

  CU_basic_set_mode(CU_BRM_VERBOSE);

  // If not inputs are provided, run everything
  if (argc == 1){
    CU_basic_run_tests();
  }

  else if (argc == 2){
    printf("running specific ts\n");
    CU_pSuite suite2run = CU_get_suite(argv[1]);
    CU_basic_run_suite(suite2run);
  }else if (argc == 3){
    printf("running specific tc from a ts\n");
    CU_pSuite suite2run = CU_get_suite(argv[1]);
    CU_pTest test2run = CU_get_test(suite2run, argv[2]);
    CU_basic_run_test(suite2run, test2run);
  }

  CU_cleanup_registry();
  return CU_get_error();
}
