//this file was generated by ../../../scripts/onnx_generator/OperatorSets.py

#include "config.h"
#include "operators/operator_set.h"

extern operator_set_opdomain opdomain_operator__ai_onnx;

operator_set_opdomain *operator_set[] = {
&opdomain_operator__ai_onnx,
#ifdef CONFIG_HAVE_DOMAIN__AI_ONNX
        &opdomain_operator__ai_onnx,
#endif
        NULL
};