//this file was generated by ../../../scripts/onnx_generator/OperatorStubs.py

#include "operators/onnx/operator__onnx__matmul__9.h"
operator_status operator__onnx__matmul__9(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__matmul__9__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__matmul__9__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__matmul__9__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__matmul__9__T_tensor_int32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__matmul__9__T_tensor_int64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__matmul__9__T_tensor_uint32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__matmul__9__T_tensor_uint64(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__maxpool__12.h"
operator_status operator__onnx__maxpool__12(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__maxpool__12__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__maxpool__12__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__maxpool__12__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__maxpool__12__T_tensor_int8(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__maxpool__12__T_tensor_uint8(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__transpose__1.h"
operator_status operator__onnx__transpose__1(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_bool(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_complex128(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_complex64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_int16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_int32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_int64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_int8(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_string(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_uint16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_uint32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_uint64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__transpose__1__T_tensor_uint8(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__relu__6.h"
operator_status operator__onnx__relu__6(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__relu__6__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__relu__6__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__relu__6__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__conv__11.h"
operator_status operator__onnx__conv__11(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__conv__11__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__conv__11__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__conv__11__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__argmax__12.h"
operator_status operator__onnx__argmax__12(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_int16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_int32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_int64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_int8(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_uint16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_uint32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_uint64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__argmax__12__T_tensor_uint8(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__add__7.h"
operator_status operator__onnx__add__7(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__add__7__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__add__7__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__add__7__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__add__7__T_tensor_int32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__add__7__T_tensor_int64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__add__7__T_tensor_uint32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__add__7__T_tensor_uint64(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__leakyrelu__6.h"
operator_status operator__onnx__leakyrelu__6(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__leakyrelu__6__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__leakyrelu__6__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__leakyrelu__6__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__reshape__5.h"
operator_status operator__onnx__reshape__5(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_bool(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_complex128(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_complex64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_int16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_int32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_int64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_int8(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_string(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_uint16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_uint32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_uint64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__reshape__5__T_tensor_uint8(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__mul__7.h"
operator_status operator__onnx__mul__7(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__mul__7__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__mul__7__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__mul__7__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__mul__7__T_tensor_int32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__mul__7__T_tensor_int64(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__mul__7__T_tensor_uint32(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__mul__7__T_tensor_uint64(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__constant__12.h"
operator_status operator__onnx__constant__12(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__batchnormalization__9.h"
operator_status operator__onnx__batchnormalization__9(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__batchnormalization__9__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__batchnormalization__9__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__batchnormalization__9__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__sigmoid__6.h"
operator_status operator__onnx__sigmoid__6(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__sigmoid__6__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__sigmoid__6__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__sigmoid__6__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }

#include "operators/onnx/operator__onnx__softmax__11.h"
operator_status operator__onnx__softmax__11(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__softmax__11__T_tensor_double(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__softmax__11__T_tensor_float(node_context *ctx) { return OP_ENOSYS; }
operator_status operator__onnx__softmax__11__T_tensor_float16(node_context *ctx) { return OP_ENOSYS; }