//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "config.h"
#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__elu__6;

operator_set_opname opname_operator__ai_onnx__elu = {
    .name = "Elu",
    .opversions = {
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__ELU__6
        &opversion_operator__ai_onnx__elu__6,
#endif
        NULL
    }
};