//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/LeakyRelu/6/operator__ai_onnx__leakyrelu__6.h"

operator_status
operator__ai_onnx__leakyrelu__6__T_tensor_double(
    node_context *ctx
)
{
    return OP_ENOSYS;
}