//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/Mul/7/operator__ai_onnx__mul__7.h"

operator_status
operator__ai_onnx__mul__7__T_tensor_int64(
    node_context *ctx
)
{
    return OP_ENOSYS;
}