//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operators/ai.onnx/Mul/7/operator__ai_onnx__mul__7.h"

operator_set_opversion opversion_operator__ai_onnx__mul__7 = {
    .version  = 7,
    .preparer = prepare_operator__ai_onnx__mul__7,
    .info = &info_operator__ai_onnx__mul__7
};