//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__relu__6.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__relu__6__T_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx__relu__6 *op_ctx = ctx->executer_context;

    Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */

    for (int i = 0; i < o_Y->n_float_data; i++) {
        o_Y->float_data[i] = i_X->float_data[i] < 0 ? 0 : i_X->float_data[i];
    }

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}