//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/GlobalAveragePool/1/operator__ai_onnx__globalaveragepool__1.h"

operator_status
operator__ai_onnx__globalaveragepool__1__T_tensor_double(
    node_context *ctx
)
{
    return OP_ENOSYS;
}