//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operators/ai.onnx/GlobalAveragePool/1/operator__ai_onnx__globalaveragepool__1.h"

operator_set_opversion opversion_operator__ai_onnx__globalaveragepool__1 = {
    .version  = 1,
    .preparer = prepare_operator__ai_onnx__globalaveragepool__1,
    .info = &info_operator__ai_onnx__globalaveragepool__1
};