//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__sigmoid__6.h"
#include "tracing.h"
#include "utils.h"
#include "math.h"

static inline
void
sigmoid(float *in, float *out, int num) {
    // Numerically stable Sigmoid implementation
    for (int i = 0; i < num; i++) 
    {
        if (in[i] >= 0)
        {
            out[i] = 1.0 / ( 1.0 + expf(-1*in[i]));
        }
        else 
        {
            out[i] = expf(in[i]) / (1.0 + expf(in[i]));
        }
    }
}

operator_status
execute_operator__ai_onnx__sigmoid__6__T_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx__sigmoid__6 *op_ctx = ctx->executer_context;

    Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */

    sigmoid(i_X->float_data, o_Y->float_data, i_X->n_float_data);

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}