
//this file was generated by ../../../scripts/onnx_generator/OperatorSanityCheck.py
#include "operators/check_operator.h"
#include "operators/onnx/operator__onnx__leakyrelu__6.h"

bool check_operator__onnx__leakyrelu__6(
    size_t                  n_input,
    Onnx__TensorProto    ** input,
    size_t                  n_attribute,
    Onnx__AttributeProto ** attribute,
    size_t                  n_output,
    Onnx__TensorProto    ** output
){
    bool valid = true;
    { // check if input tensors have valid types
        uint32_t types_X[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        check_operator_condition_tensor conditions[1] = {
            {
                .skip = false,
                .name = "X",
                .optional = false,
                .n_types = 3,
                .types  = types_X
            }
        };
        valid &= check_operator_tensors("operator__onnx__leakyrelu__6 input",
                                         1,
                                         conditions,
                                         input);
    }
    { // check if output tensors have valid types
        uint32_t types_Y[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        check_operator_condition_tensor conditions[1] = {
            {
                .skip = false,
                .name = "Y",
                .optional = false,
                .n_types = 3,
                .types  = types_Y
            }
        };
        valid &= check_operator_tensors("operator__onnx__leakyrelu__6 output",
                                         1,
                                         conditions,
                                         output);
    }
    { // check if attributes have valid types
        check_operator_condition_attribute conditions[1] = {
            {
                .skip = false,
                .name = "alpha",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__FLOAT,
            }
        };
        valid &= check_operator_attributes("operator__onnx__leakyrelu__6",
                                           1,
                                           conditions,
                                           attribute);
    }
    { // check if multiple tensors constrained by 'T' have same type
        check_operator_condition_constraint conditions_input[1] = {
            {
                .skip = false,
                .name = "X",
                .optional = false
            }
        };
        check_operator_condition_constraint conditions_output[1] = {
            {
                .skip = false,
                .name = "Y",
                .optional = false
            }
        };
        valid &= check_operator_constraint("operator__onnx__leakyrelu__6 T",
                                           1,
                                           conditions_input,
                                           input,
                                           1,
                                           conditions_output,
                                           output);
    }
    return valid;
}
