
//this file was generated by ../../../scripts/onnx_generator/OperatorSanityCheck.py
#include "operators/check_operator.h"
#include "operators/onnx/operator__onnx__conv__11.h"

bool check_operator__onnx__conv__11(
    size_t                  n_input,
    Onnx__TensorProto    ** input,
    size_t                  n_attribute,
    Onnx__AttributeProto ** attribute,
    size_t                  n_output,
    Onnx__TensorProto    ** output
){
    bool valid = true;
    { // check if input tensors have valid types
        uint32_t types_X[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_W[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_B[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        check_operator_condition_tensor conditions[3] = {
            {
                .skip = false,
                .name = "X",
                .optional = false,
                .n_types = 3,
                .types  = types_X
            },{
                .skip = false,
                .name = "W",
                .optional = false,
                .n_types = 3,
                .types  = types_W
            },{
                .skip = false,
                .name = "B",
                .optional = true,
                .n_types = 3,
                .types  = types_B
            }
        };
        valid &= check_operator_tensors("operator__onnx__conv__11 input",
                                         3,
                                         conditions,
                                         input);
    }
    { // check if output tensors have valid types
        uint32_t types_Y[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        check_operator_condition_tensor conditions[1] = {
            {
                .skip = false,
                .name = "Y",
                .optional = false,
                .n_types = 3,
                .types  = types_Y
            }
        };
        valid &= check_operator_tensors("operator__onnx__conv__11 output",
                                         1,
                                         conditions,
                                         output);
    }
    { // check if attributes have valid types
        check_operator_condition_attribute conditions[6] = {
            {
                .skip = false,
                .name = "auto_pad",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__STRING,
            },{
                .skip = false,
                .name = "dilations",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS,
            },{
                .skip = false,
                .name = "group",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INT,
            },{
                .skip = false,
                .name = "kernel_shape",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS,
            },{
                .skip = false,
                .name = "pads",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS,
            },{
                .skip = false,
                .name = "strides",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS,
            }
        };
        valid &= check_operator_attributes("operator__onnx__conv__11",
                                           6,
                                           conditions,
                                           attribute);
    }
    { // check if multiple tensors constrained by 'T' have same type
        check_operator_condition_constraint conditions_input[3] = {
            {
                .skip = false,
                .name = "X",
                .optional = false
            },{
                .skip = false,
                .name = "W",
                .optional = false
            },{
                .skip = false,
                .name = "B",
                .optional = true
            }
        };
        check_operator_condition_constraint conditions_output[1] = {
            {
                .skip = false,
                .name = "Y",
                .optional = false
            }
        };
        valid &= check_operator_constraint("operator__onnx__conv__11 T",
                                           3,
                                           conditions_input,
                                           input,
                                           1,
                                           conditions_output,
                                           output);
    }
    return valid;
}
