
//this file was generated by ../../../scripts/onnx_generator/OperatorSanityCheck.py
#include "operators/check_operator.h"
#include "operators/onnx/operator__onnx__argmax__12.h"

bool check_operator__onnx__argmax__12(
    size_t                  n_input,
    Onnx__TensorProto    ** input,
    size_t                  n_attribute,
    Onnx__AttributeProto ** attribute,
    size_t                  n_output,
    Onnx__TensorProto    ** output
){
    bool valid = true;
    { // check if input tensors have valid types
        uint32_t types_data[11] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16,
            ONNX__TENSOR_PROTO__DATA_TYPE__INT16,
            ONNX__TENSOR_PROTO__DATA_TYPE__INT32,
            ONNX__TENSOR_PROTO__DATA_TYPE__INT64,
            ONNX__TENSOR_PROTO__DATA_TYPE__INT8,
            ONNX__TENSOR_PROTO__DATA_TYPE__UINT16,
            ONNX__TENSOR_PROTO__DATA_TYPE__UINT32,
            ONNX__TENSOR_PROTO__DATA_TYPE__UINT64,
            ONNX__TENSOR_PROTO__DATA_TYPE__UINT8
        };
        check_operator_condition_tensor conditions[1] = {
            {
                .skip = false,
                .name = "data",
                .optional = false,
                .n_types = 11,
                .types  = types_data
            }
        };
        valid &= check_operator_tensors("operator__onnx__argmax__12 input",
                                         1,
                                         conditions,
                                         input);
    }
    { // check if output tensors have valid types
        uint32_t types_reduced[1] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__INT64
        };
        check_operator_condition_tensor conditions[1] = {
            {
                .skip = false,
                .name = "reduced",
                .optional = false,
                .n_types = 1,
                .types  = types_reduced
            }
        };
        valid &= check_operator_tensors("operator__onnx__argmax__12 output",
                                         1,
                                         conditions,
                                         output);
    }
    { // check if attributes have valid types
        check_operator_condition_attribute conditions[3] = {
            {
                .skip = false,
                .name = "axis",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INT,
            },{
                .skip = false,
                .name = "keepdims",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INT,
            },{
                .skip = false,
                .name = "select_last_index",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INT,
            }
        };
        valid &= check_operator_attributes("operator__onnx__argmax__12",
                                           3,
                                           conditions,
                                           attribute);
    }
    { // check if multiple tensors constrained by 'T' have same type
        check_operator_condition_constraint conditions_input[1] = {
            {
                .skip = false,
                .name = "data",
                .optional = false
            }
        };
        check_operator_condition_constraint conditions_output[1] = {
            {
                .skip = true,
                .name = "reduced",
                .optional = false
            }
        };
        valid &= check_operator_constraint("operator__onnx__argmax__12 T",
                                           1,
                                           conditions_input,
                                           input,
                                           1,
                                           conditions_output,
                                           output);
    }
    return valid;
}
