
//this file was generated by ../../../scripts/onnx_generator/OperatorSanityCheck.py
#include "operators/check_operator.h"
#include "operators/onnx/operator__onnx__batchnormalization__9.h"

bool check_operator__onnx__batchnormalization__9(
    size_t                  n_input,
    Onnx__TensorProto    ** input,
    size_t                  n_attribute,
    Onnx__AttributeProto ** attribute,
    size_t                  n_output,
    Onnx__TensorProto    ** output
){
    bool valid = true;
    { // check if input tensors have valid types
        uint32_t types_X[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_scale[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_B[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_mean[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_var[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        check_operator_condition_tensor conditions[5] = {
            {
                .skip = false,
                .name = "X",
                .optional = false,
                .n_types = 3,
                .types  = types_X
            },{
                .skip = false,
                .name = "scale",
                .optional = false,
                .n_types = 3,
                .types  = types_scale
            },{
                .skip = false,
                .name = "B",
                .optional = false,
                .n_types = 3,
                .types  = types_B
            },{
                .skip = false,
                .name = "mean",
                .optional = false,
                .n_types = 3,
                .types  = types_mean
            },{
                .skip = false,
                .name = "var",
                .optional = false,
                .n_types = 3,
                .types  = types_var
            }
        };
        valid &= check_operator_tensors("operator__onnx__batchnormalization__9 input",
                                         5,
                                         conditions,
                                         input);
    }
    { // check if output tensors have valid types
        uint32_t types_Y[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_mean[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_var[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_saved_mean[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        uint32_t types_saved_var[3] = {
            ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
            ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
        };
        check_operator_condition_tensor conditions[5] = {
            {
                .skip = false,
                .name = "Y",
                .optional = false,
                .n_types = 3,
                .types  = types_Y
            },{
                .skip = false,
                .name = "mean",
                .optional = true,
                .n_types = 3,
                .types  = types_mean
            },{
                .skip = false,
                .name = "var",
                .optional = true,
                .n_types = 3,
                .types  = types_var
            },{
                .skip = false,
                .name = "saved_mean",
                .optional = true,
                .n_types = 3,
                .types  = types_saved_mean
            },{
                .skip = false,
                .name = "saved_var",
                .optional = true,
                .n_types = 3,
                .types  = types_saved_var
            }
        };
        valid &= check_operator_tensors("operator__onnx__batchnormalization__9 output",
                                         5,
                                         conditions,
                                         output);
    }
    { // check if attributes have valid types
        check_operator_condition_attribute conditions[2] = {
            {
                .skip = false,
                .name = "epsilon",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__FLOAT,
            },{
                .skip = false,
                .name = "momentum",
                .optional = false,
                .type = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__FLOAT,
            }
        };
        valid &= check_operator_attributes("operator__onnx__batchnormalization__9",
                                           2,
                                           conditions,
                                           attribute);
    }
    { // check if multiple tensors constrained by 'T' have same type
        check_operator_condition_constraint conditions_input[5] = {
            {
                .skip = false,
                .name = "X",
                .optional = false
            },{
                .skip = false,
                .name = "scale",
                .optional = false
            },{
                .skip = false,
                .name = "B",
                .optional = false
            },{
                .skip = false,
                .name = "mean",
                .optional = false
            },{
                .skip = false,
                .name = "var",
                .optional = false
            }
        };
        check_operator_condition_constraint conditions_output[5] = {
            {
                .skip = false,
                .name = "Y",
                .optional = false
            },{
                .skip = false,
                .name = "mean",
                .optional = true
            },{
                .skip = false,
                .name = "var",
                .optional = true
            },{
                .skip = false,
                .name = "saved_mean",
                .optional = true
            },{
                .skip = false,
                .name = "saved_var",
                .optional = true
            }
        };
        valid &= check_operator_constraint("operator__onnx__batchnormalization__9 T",
                                           5,
                                           conditions_input,
                                           input,
                                           5,
                                           conditions_output,
                                           output);
    }
    return valid;
}
