//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "config.h"
#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__globalaveragepool__1;

operator_set_opname opname_operator__ai_onnx__globalaveragepool = {
    .name = "GlobalAveragePool",
    .opversions = {
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__GLOBALAVERAGEPOOL__1
        &opversion_operator__ai_onnx__globalaveragepool__1,
#endif
        NULL
    }
};