//this file was generated by ../../../../scripts/onnx_generator/OperatorSets.py

#include "config.h"
#include "operators/operator_set.h"

extern operator_set_opname opname_operator__ai_onnx__matmul;
extern operator_set_opname opname_operator__ai_onnx__identity;
extern operator_set_opname opname_operator__ai_onnx__maxpool;
extern operator_set_opname opname_operator__ai_onnx__transpose;
extern operator_set_opname opname_operator__ai_onnx__clip;
extern operator_set_opname opname_operator__ai_onnx__elu;
extern operator_set_opname opname_operator__ai_onnx__relu;
extern operator_set_opname opname_operator__ai_onnx__conv;
extern operator_set_opname opname_operator__ai_onnx__argmax;
extern operator_set_opname opname_operator__ai_onnx__add;
extern operator_set_opname opname_operator__ai_onnx__leakyrelu;
extern operator_set_opname opname_operator__ai_onnx__reshape;
extern operator_set_opname opname_operator__ai_onnx__globalaveragepool;
extern operator_set_opname opname_operator__ai_onnx__mul;
extern operator_set_opname opname_operator__ai_onnx__constant;
extern operator_set_opname opname_operator__ai_onnx__batchnormalization;
extern operator_set_opname opname_operator__ai_onnx__sigmoid;
extern operator_set_opname opname_operator__ai_onnx__softmax;

operator_set_opdomain opdomain_operator__ai_onnx = {
    .name = "ai.onnx",
    .opnames = {
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__MATMUL
        &opname_operator__ai_onnx__matmul,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__IDENTITY
        &opname_operator__ai_onnx__identity,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__MAXPOOL
        &opname_operator__ai_onnx__maxpool,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__TRANSPOSE
        &opname_operator__ai_onnx__transpose,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__CLIP
        &opname_operator__ai_onnx__clip,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__ELU
        &opname_operator__ai_onnx__elu,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__RELU
        &opname_operator__ai_onnx__relu,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__CONV
        &opname_operator__ai_onnx__conv,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__ARGMAX
        &opname_operator__ai_onnx__argmax,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__ADD
        &opname_operator__ai_onnx__add,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__LEAKYRELU
        &opname_operator__ai_onnx__leakyrelu,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__RESHAPE
        &opname_operator__ai_onnx__reshape,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__GLOBALAVERAGEPOOL
        &opname_operator__ai_onnx__globalaveragepool,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__MUL
        &opname_operator__ai_onnx__mul,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__CONSTANT
        &opname_operator__ai_onnx__constant,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__BATCHNORMALIZATION
        &opname_operator__ai_onnx__batchnormalization,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__SIGMOID
        &opname_operator__ai_onnx__sigmoid,
#endif
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__SOFTMAX
        &opname_operator__ai_onnx__softmax,
#endif
        NULL
    }
};