//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__identity__1.h"

operator_status
operator__onnx__identity__1__T_tensor_complex64(
    node_context *ctx
)
{
    return OP_ENOSYS;
}