//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__batchnormalization__9.h"

operator_status
operator__onnx__batchnormalization__9(
    node_context *ctx
)
{
    return OP_ENOSYS;
}