//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__argmax__12.h"

operator_status
operator__onnx__argmax__12(
    node_context *ctx
)
{
    return OP_ENOSYS;
}