//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__clip__12.h"

operator_status
operator__onnx__clip__12__T_tensor_float(
    node_context *ctx
)
{
    return OP_ENOSYS;
}