//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__conv__11.h"

operator_status
operator__onnx__conv__11__T_tensor_float16(
    node_context *ctx
)
{
    return OP_ENOSYS;
}