//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__add__7.h"

operator_status
operator__onnx__add__7(
    node_context *ctx
)
{
    return OP_ENOSYS;
}