//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__matmul__9.h"

operator_status
operator__onnx__matmul__9__T_tensor_double(
    node_context *ctx
)
{
    return OP_ENOSYS;
}