//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__reshape__5.h"

operator_status
operator__onnx__reshape__5__T_tensor_uint16(
    node_context *ctx
)
{
    return OP_ENOSYS;
}