//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__transpose__1.h"

operator_status
operator__onnx__transpose__1__T_tensor_string(
    node_context *ctx
)
{
    return OP_ENOSYS;
}