//this file was generated by ../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/onnx/operator__onnx__elu__6.h"

operator_status
operator__onnx__elu__6__T_tensor_float16(
    node_context *ctx
)
{
    return OP_ENOSYS;
}