//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/Elu/6/operator__ai_onnx__elu__6.h"

operator_status
operator__ai_onnx__elu__6(
    node_context *ctx
)
{
    return OP_ENOSYS;
}