//this file was generated by ../../../../../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__ELU__6_H
# define OPERATOR_OPERATOR__AI_ONNX__ELU__6_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Elu' version 6
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Elu takes one input data (Tensor<T>) and produces one output data
 * (Tensor<T>) where the function `f(x) = alpha * (exp(x) - 1.) for x <
 * 0`, `f(x) = x for x >= 0`., is applied to the tensor elementwise.
 *
 * Constraint T:
 *   Constrain input and output types to float tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Input T X:
 *   1D input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Output T Y:
 *   1D input tensor
 *   Allowed Types: tensor_double, tensor_float, tensor_float16
 * Attribute FLOAT alpha (optional):
 *   Coefficient of ELU.
 *
 * @since version 6
 *
 * @see io/onnx/onnx/defs/math/defs.cc:413
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Elu
 */

operator_status
prepare_operator__ai_onnx__elu__6(
    node_context *ctx
);

extern operator_info info_operator__ai_onnx__elu__6;

typedef struct {
    float alpha;

} context_operator__ai_onnx__elu__6;

operator_executer
resolve_operator__ai_onnx__elu__6(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__elu__6__T_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__elu__6__T_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__elu__6__T_tensor_float16(
    node_context *ctx
);

# endif