//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "config.h"
#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__sigmoid__6;

operator_set_opname opname_operator__ai_onnx__sigmoid = {
    .name = "Sigmoid",
    .opversions = {
#ifdef CONFIG_HAVE_OPERATOR__AI_ONNX__SIGMOID__6
        &opversion_operator__ai_onnx__sigmoid__6,
#endif
        NULL
    }
};