//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__clip__12.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__clip__12(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_input = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_min = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_max = searchInputByName(ctx, 2);

    TRACE_TENSOR(2, true, i_input);
    // TRACE_TENSOR(2, min, i_min);
    // TRACE_TENSOR(2, max, i_max);

    Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__clip__12 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__clip__12));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */

    o_output->has_raw_data = 0;
    o_output->data_type = i_input->data_type;
    o_output->n_dims = i_input->n_dims;
    o_output->dims = ARRAYDUP(i_input->dims, i_input->n_dims);

    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_output);

    TRACE_TENSOR(2, true, o_output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = resolve_operator__ai_onnx__clip__12(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}