//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/Reshape/5/operator__ai_onnx__reshape__5.h"

operator_status
operator__ai_onnx__reshape__5__T_tensor_float16(
    node_context *ctx
)
{
    return OP_ENOSYS;
}