//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operator__ai_onnx__reshape__5.h"

operator_set_opversion opversion_operator__ai_onnx__reshape__5 = {
    .version  = 5,
    .preparer = prepare_operator__ai_onnx__reshape__5,
    .info = &info_operator__ai_onnx__reshape__5
};