//this file was generated by ../../../../../scripts/onnx_generator/OperatorTypeResolver.py
#include "operators/onnx/operator__onnx__batchnormalization__12.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer resolve_operator__onnx__batchnormalization__12(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T = 0;
if (ctx->inputs[0]) {
    T = ctx->inputs[0]->data_type;
}
uint32_t T1 = 0;
if (ctx->inputs[5]) {
    T1 = ctx->inputs[5]->data_type;
}
    switch ( T ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { switch ( T1 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BOOL: { executer = (operator_executer) &operator__onnx__batchnormalization__12__T_tensor_double__T1_tensor_bool; break; }
    default: {
        fprintf(stderr, "no matching type for operator__onnx__batchnormalization__12 and constraint 'T1' with type '%s' found!\n",operator_info_tensorType2str(T1));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { switch ( T1 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BOOL: { executer = (operator_executer) &operator__onnx__batchnormalization__12__T_tensor_float__T1_tensor_bool; break; }
    default: {
        fprintf(stderr, "no matching type for operator__onnx__batchnormalization__12 and constraint 'T1' with type '%s' found!\n",operator_info_tensorType2str(T1));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { switch ( T1 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BOOL: { executer = (operator_executer) &operator__onnx__batchnormalization__12__T_tensor_float16__T1_tensor_bool; break; }
    default: {
        fprintf(stderr, "no matching type for operator__onnx__batchnormalization__12 and constraint 'T1' with type '%s' found!\n",operator_info_tensorType2str(T1));
        break;
    }
} break; }
    default: {
        fprintf(stderr, "no matching type for operator__onnx__batchnormalization__12 and constraint 'T' with type '%s' found!\n",operator_info_tensorType2str(T));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}