
//this file was generated by ../../../scripts/onnx_generator/OperatorTypeResolver.py
#include "operators/onnx/operator__onnx__maxpool__12.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer resolve_operator__onnx__maxpool__12(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T = 0;
    if (ctx->inputs[0]) {
        T = ctx->inputs[0]->data_type;
    }

    /* This file has been edited manually */
    switch ( T ) {
        case 0: //constrained tensor is not set (maybe optional?), just take next case
        case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &operator__onnx__maxpool__12__T_tensor_float__I_tensor_int64; break; }
        /* Edited manually */
        default: {
            fprintf(stderr, "[maxpool] no matching type for constraint 'T' found!\n");
            break;
        }
    }
  }
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}
