//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/Conv/11/operator__ai_onnx__conv__11.h"

operator_status
operator__ai_onnx__conv__11__T_tensor_double(
    node_context *ctx
)
{
    return OP_ENOSYS;
}