//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__softmax__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__softmax__11(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_input = searchInputByName(ctx, 0);

    TRACE_TENSOR(2, true, i_input);

    Onnx__AttributeProto *a_axis = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"axis");

    TRACE_ATTRIBUTE(2, a_axis, a_axis);

    Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    int64_t default_axis = 1;

    context_operator__ai_onnx__softmax__11 *op_ctx = NULL;
    op_ctx = malloc(sizeof(context_operator__ai_onnx__softmax__11));
    TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    op_ctx->axis = a_axis?a_axis->i:default_axis;
    //wrap axis if negative
    if (op_ctx->axis < 0) {
        op_ctx->axis += i_input->n_dims;
    }
    op_ctx->N = 1;
    op_ctx->D = 1;

    TRACE_VAR(2, true, op_ctx->axis, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */

    o_output->has_raw_data = 0;
    o_output->data_type    = i_input->data_type;
    o_output->n_dims       = i_input->n_dims;
    o_output->dims         = ARRAYDUP(i_input->dims, i_input->n_dims);

    for (int i = 0; i < i_input->n_dims; i++) {
        if (i < op_ctx->axis) {
            op_ctx->N *= i_input->dims[i];
        } else {
            op_ctx->D *= i_input->dims[i];
        }
        o_output->dims[i] = i_input->dims[i];
    }

    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_output);

    TRACE_TENSOR(2, true, o_output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = resolve_operator__ai_onnx__softmax__11(ctx);
    ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}