//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__add__7.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__add__7__T_tensor_float16(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, true, i_A);
    // TRACE_TENSOR(2, true, i_B);

    // context_operator__ai_onnx__add__7 *op_ctx = ctx->executer_context;

    

    

    // Onnx__TensorProto *o_C = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_C);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}