//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__add__7.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__add__7(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, true, i_A);
    // TRACE_TENSOR(2, true, i_B);

    

    

    // Onnx__TensorProto *o_C = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_C);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__add__7 *op_ctx = ctx->executer_context;

    

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_C);
    // free(o_C->dims);

    TRACE_EXIT(1);
}