

class OperatorImplementation:
    _template_file = '''
//this file was generated by {script}
#include "{header_name}.h"

{function}

'''

    _template_function = ''' 
int {operator_name}(
  size_t                  n_input,
  Onnx__TensorProto    ** input,
  size_t                  n_attribute,
  Onnx__AttributeProto ** attribute,
  size_t                  n_output,
  Onnx__TensorProto    ** output
){{

{checks_sameType}

{checks_ofType}

{switch}

}}
'''
    def __init__(self, schema, path):
      self.schema = schema
    
    def __text__(self):
      pass

    def __str__(self):
      pass