//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__identity__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__identity__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    __attribute__((unused))
    Onnx__TensorProto *i_input = searchInputByName(ctx, 0);

    TRACE_TENSOR(2, true, i_input);

    // context_operator__ai_onnx__identity__1 *op_ctx = ctx->executer_context;

    __attribute__((unused))
    Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */
    // nothing to do

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}