//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/Identity/1/operator__ai_onnx__identity__1.h"

operator_status
operator__ai_onnx__identity__1__T_tensor_string(
    node_context *ctx
)
{
    return OP_ENOSYS;
}