//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operator__ai_onnx__identity__1.h"

operator_set_opversion opversion_operator__ai_onnx__identity__1 = {
    .version  = 1,
    .preparer = prepare_operator__ai_onnx__identity__1,
    .info = &info_operator__ai_onnx__identity__1
};