//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operators/ai.onnx/ConvTranspose/11/operator__ai_onnx__convtranspose__11.h"

operator_set_opversion opversion_operator__ai_onnx__convtranspose__11 = {
    .version  = 11,
    .preparer = prepare_operator__ai_onnx__convtranspose__11,
    .info = &info_operator__ai_onnx__convtranspose__11
};