//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__transpose__1.h"
#include "tracing.h"
#include "utils.h"
#include "index.h"

operator_status
execute_operator__ai_onnx__transpose__1__T_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    TRACE_TENSOR(2, true, i_data);

    context_operator__ai_onnx__transpose__1 *op_ctx = ctx->executer_context;

    size_t n_perm = op_ctx->n_perm;
    int64_t* perm = op_ctx->perm;

    TRACE_ARRAY(2, true, perm, , n_perm, "%" PRId64);

    Onnx__TensorProto *o_transposed = searchOutputByName(ctx, 0);

    TRACE_TENSOR(2, true, o_transposed);

    /* DO CALCULATION HERE */

    int n_dims = o_transposed->n_dims;
    int index[n_dims];
    for (int i = 0; i < n_dims; i++) {
        index[i] = 0;
    }

    //calculate offset of each dimension
    int offset[n_dims];
    offset[n_dims-1] = 1;
    for (int i = n_dims-2; i >= 0; i--) {
        offset[i] = o_transposed->dims[i+1] * offset[i+1];
    }

    for(int i = 0; i < o_transposed->n_float_data; i++) {
        for (int n = n_dims-1; n > 0 ; n--) {
            if ( index[n] < i_data->dims[n]) break;
            index[n] = 0;
            index[n-1]++;
        }
        if ( index[0] >= i_data->dims[0]) break;

        int pos = 0;
        for (int n = 0; n < n_perm; n++) {
            pos += index[perm[n]] * offset[n];
        }
        o_transposed->float_data[pos] = i_data->float_data[i];
        index[n_dims-1]++;
    }

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}