//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__transpose__1.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__transpose__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_data);

    // Onnx__AttributeProto *a_perm = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"perm");

    // TRACE_ATTRIBUTE(2, a_perm, a_perm);

    // Onnx__TensorProto *o_transposed = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_transposed);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__transpose__1 *op_ctx = ctx->executer_context;

    // TRACE_ARRAY(2, true, op_ctx->perm, , op_ctx->n_perm, "%" PRId64);

    // free(op_ctx->perm);

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_transposed);
    // free(o_transposed->dims);

    TRACE_EXIT(1);
}