//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTypeResolver.py
#include "operator__ai_onnx__transpose__1.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer
resolve_operator__ai_onnx__transpose__1(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T = 0;
if (ctx->inputs[0]) {
    T = ctx->inputs[0]->data_type;
}
    switch ( T ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BOOL: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_bool; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX128: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_complex128; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX64: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_complex64; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_float16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT16: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_int16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_int64; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_int8; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__STRING: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_string; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT16: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_uint16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT32: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_uint32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT64: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_uint64; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { executer = (operator_executer) &execute_operator__ai_onnx__transpose__1__T_tensor_uint8; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__transpose__1 and constraint 'T' with type '%s' found!\n",operator_info_tensorType2str(T));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}