//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/MatMul/9/operator__ai_onnx__matmul__9.h"

operator_status
operator__ai_onnx__matmul__9(
    node_context *ctx
)
{
    return OP_ENOSYS;
}