//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operators/ai.onnx/MatMul/9/operator__ai_onnx__matmul__9.h"

operator_set_opversion opversion_operator__ai_onnx__matmul__9 = {
    .version  = 9,
    .preparer = prepare_operator__ai_onnx__matmul__9,
    .info = &info_operator__ai_onnx__matmul__9
};