//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operator__ai_onnx__batchnormalization__9.h"

operator_set_opversion opversion_operator__ai_onnx__batchnormalization__9 = {
    .version  = 9,
    .preparer = prepare_operator__ai_onnx__batchnormalization__9,
    .info = &info_operator__ai_onnx__batchnormalization__9
};