
//this file was generated by ../../scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__ONNX__ADD__7_H
# define OPERATOR_OPERATOR__ONNX__ADD__7_H

# include "operators/operator.h"
# include "operators/operator_stub.h"

typedef struct operator_context_input__operator__onnx__add__7 {
    size_t length;
    operator_tensor *A;
operator_tensor *B;
} operator_context_input_operator__onnx__add__7;

typedef struct operator_context_output__operator__onnx__add__7 {
    size_t length;
    operator_tensor *C;
} operator_context_output_operator__onnx__add__7;

typedef struct operator_context_attribute__operator__onnx__add__7 {
    size_t length;

} operator_context_attribute_operator__onnx__add__7;

typedef struct operator_context__operator__onnx__add__7 {
    struct operator_context_input__operator__onnx__add__7     *input;
    struct operator_context_output__operator__onnx__add__7    *output;
    struct operator_context_attribute__operator__onnx__add__7 *attribute;
    operator_executer                          operator;
} operator_context__operator__onnx__add__7;

/**
 * onnx operator 'Add' version 7
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Performs element-wise binary addition (with Numpy-style broadcasting
 * support). This operator supports **multidirectional (i.e., Numpy-style)
 * broadcasting**; for more details please check [the doc](Broadcasting.md).
 *
 * Constraint T:
 *   Constrain input and output types to high-precision numeric tensors.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int32,
 *                  tensor_int64, tensor_uint32, tensor_uint64
 * Input T A:
 *   First operand.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int32,
 *                  tensor_int64, tensor_uint32, tensor_uint64
 *
 * Input T B:
 *   Second operand.
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int32,
 *                  tensor_int64, tensor_uint32, tensor_uint64
 * Output T C:
 *   Result, has same element type as two inputs
 *   Allowed Types: tensor_double, tensor_float, tensor_float16, tensor_int32,
 *                  tensor_int64, tensor_uint32, tensor_uint64

 *
 * @since version 7
 *
 * @see ../../../../../../travis/build/onnx/wheel-builder/onnx/onnx/defs/math/defs.cc:113
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Add
 */
operator_status operator__onnx__add__7(
    operator_context__operator__onnx__add__7 *ctx
);

operator_executer resolve_operator__onnx__add__7(
    operator_context__operator__onnx__add__7 *ctx
);

extern __attribute__((weak))
operator_status operator__onnx__add__7__T_tensor_double(
    operator_context__operator__onnx__add__7 *ctx
);
extern __attribute__((weak))
operator_status operator__onnx__add__7__T_tensor_float(
    operator_context__operator__onnx__add__7 *ctx
);
extern __attribute__((weak))
operator_status operator__onnx__add__7__T_tensor_float16(
    operator_context__operator__onnx__add__7 *ctx
);
extern __attribute__((weak))
operator_status operator__onnx__add__7__T_tensor_int32(
    operator_context__operator__onnx__add__7 *ctx
);
extern __attribute__((weak))
operator_status operator__onnx__add__7__T_tensor_int64(
    operator_context__operator__onnx__add__7 *ctx
);
extern __attribute__((weak))
operator_status operator__onnx__add__7__T_tensor_uint32(
    operator_context__operator__onnx__add__7 *ctx
);
extern __attribute__((weak))
operator_status operator__onnx__add__7__T_tensor_uint64(
    operator_context__operator__onnx__add__7 *ctx
);
# endif
