//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__maxpool__12.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__maxpool__12__T_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    TRACE_TENSOR(2, true, i_X);

    context_operator__ai_onnx__maxpool__12 *op_ctx = ctx->executer_context;

    __attribute__((unused))
    char* auto_pad = op_ctx->auto_pad;
    // int64_t ceil_mode = op_ctx->ceil_mode;
    // size_t n_dilations = op_ctx->n_dilations;
    // int64_t* dilations = op_ctx->dilations;
    __attribute__((unused))
    size_t n_kernel_shape = op_ctx->n_kernel_shape;
    __attribute__((unused))
    int64_t* kernel_shape = op_ctx->kernel_shape;
    __attribute__((unused))
    size_t n_pads = op_ctx->n_pads;
    __attribute__((unused))
    int64_t* pads_end = op_ctx->pads_end;
    __attribute__((unused))
    int64_t* pads_begin = op_ctx->pads_begin;
    // int64_t storage_order = op_ctx->storage_order;
    __attribute__((unused))
    size_t n_strides = op_ctx->n_strides;
    __attribute__((unused))
    int64_t* strides = op_ctx->strides;

    TRACE_VAR(2, true, auto_pad, "\"%s\"");
    // TRACE_VAR(2, true, ceil_mode, "%" PRId64);
    // TRACE_ARRAY(2, true, dilations, , n_dilations, "%" PRId64);
    TRACE_ARRAY(2, true, kernel_shape, , n_kernel_shape, "%" PRId64);
    TRACE_ARRAY(2, true, pads_begin, , n_pads, "%" PRId64);
    TRACE_ARRAY(2, true, pads_end, , n_pads, "%" PRId64);
    // TRACE_VAR(2, true, storage_order, "%" PRId64);
    TRACE_ARRAY(2, true, strides, , n_strides, "%" PRId64);

    Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Indices = searchOutputByName(ctx, 1);

    TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, Indices, o_Indices);

    /* DO CALCULATION HERE */

    int64_t h_kernel = kernel_shape[0];
    int64_t w_kernel = kernel_shape[1];

    int64_t h_stride = strides[0];
    int64_t w_stride = strides[1];

    // int64_t h_pad_aux = pads_begin[0] + pads_end[0];
    // int64_t w_pad_aux = pads_begin[1] + pads_end[1];

    int64_t h_pad = pads_begin[0];
    int64_t w_pad = pads_begin[1];

    int b,i,j,k,m,n;
    for(b = 0; b < o_Y->dims[0]; ++b){
        for(k = 0; k < o_Y->dims[1]; ++k){
            for(i = 0; i < o_Y->dims[2]; ++i){
                for(j = 0; j < o_Y->dims[3]; ++j){
                    int out_index = j + o_Y->dims[3]*(i + o_Y->dims[2]*(k + i_X->dims[1]*b));
                    float max = -999999; // TODO
                    for(n = 0; n < h_kernel; ++n){
                        for(m = 0; m < w_kernel; ++m){
                            int cur_h = i*h_stride + n - h_pad;
                            int cur_w = j*w_stride + m - w_pad;
                            int index = cur_w + i_X->dims[3]*(cur_h + i_X->dims[2]*(k + b*i_X->dims[1]));
                            int valid = (cur_h >= 0 && cur_h < (i_X->dims[2]) &&
                                       cur_w >= 0 && cur_w < (i_X->dims[3]));
                            float val = (valid != 0) ? i_X->float_data[index] : -999999; //TODO
                            max = (val > max ? val : max);
                        }
                    }
                    o_Y->float_data[out_index] = max;
                }
            }
        }
    }

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}