//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__maxpool__12.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__maxpool__12__T_tensor_float16(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // context_operator__ai_onnx__maxpool__12 *op_ctx = ctx->executer_context;

    // char* auto_pad = op_ctx->auto_pad;
    // int64_t ceil_mode = op_ctx->ceil_mode;
    // size_t n_dilations = op_ctx->n_dilations;
    // int64_t* dilations = op_ctx->dilations;
    // size_t n_kernel_shape = op_ctx->n_kernel_shape;
    // int64_t* kernel_shape = op_ctx->kernel_shape;
    // size_t n_pads = op_ctx->n_pads;
    // int64_t* pads = op_ctx->pads;
    // int64_t storage_order = op_ctx->storage_order;
    // size_t n_strides = op_ctx->n_strides;
    // int64_t* strides = op_ctx->strides;

    // TRACE_VAR(2, true, auto_pad, "\"%s\"");
    // TRACE_VAR(2, true, ceil_mode, "%" PRId64);
    // TRACE_ARRAY(2, true, dilations, , n_dilations, "%" PRId64);
    // TRACE_ARRAY(2, true, kernel_shape, , n_kernel_shape, "%" PRId64);
    // TRACE_ARRAY(2, true, pads, , n_pads, "%" PRId64);
    // TRACE_VAR(2, true, storage_order, "%" PRId64);
    // TRACE_ARRAY(2, true, strides, , n_strides, "%" PRId64);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Indices = searchOutputByName(ctx, 1);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, Indices, o_Indices);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}