//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__maxpool__12.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__maxpool__12(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_auto_pad = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"auto_pad");
    // Onnx__AttributeProto *a_ceil_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"ceil_mode");
    // Onnx__AttributeProto *a_dilations = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"dilations");
    // Onnx__AttributeProto *a_kernel_shape = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"kernel_shape");
    // Onnx__AttributeProto *a_pads = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"pads");
    // Onnx__AttributeProto *a_storage_order = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"storage_order");
    // Onnx__AttributeProto *a_strides = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"strides");

    // TRACE_ATTRIBUTE(2, a_auto_pad, a_auto_pad);
    // TRACE_ATTRIBUTE(2, a_ceil_mode, a_ceil_mode);
    // TRACE_ATTRIBUTE(2, a_dilations, a_dilations);
    // TRACE_ATTRIBUTE(2, true, a_kernel_shape);
    // TRACE_ATTRIBUTE(2, a_pads, a_pads);
    // TRACE_ATTRIBUTE(2, a_storage_order, a_storage_order);
    // TRACE_ATTRIBUTE(2, a_strides, a_strides);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Indices = searchOutputByName(ctx, 1);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, Indices, o_Indices);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__maxpool__12 *op_ctx = ctx->executer_context;

    // TRACE_VAR(2, true, op_ctx->auto_pad, "\"%s\"");
    // TRACE_VAR(2, true, op_ctx->ceil_mode, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->dilations, , op_ctx->n_dilations, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->kernel_shape, , op_ctx->n_kernel_shape, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->pads, , op_ctx->n_pads, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->storage_order, "%" PRId64);
    // TRACE_ARRAY(2, true, op_ctx->strides, , op_ctx->n_strides, "%" PRId64);

    // free(op_ctx->auto_pad);
    // free(op_ctx->dilations);
    // free(op_ctx->kernel_shape);
    // free(op_ctx->pads);
    // free(op_ctx->strides);

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Y);
    // free(o_Y->dims);
    // freeTensorData(o_Indices);
    // free(o_Indices->dims);

    TRACE_EXIT(1);
}