//this file was generated by ../../../../../../scripts/onnx_generator/OperatorStubs.py
#include "operators/ai.onnx/MaxPool/12/operator__ai_onnx__maxpool__12.h"

operator_status
operator__ai_onnx__maxpool__12(
    node_context *ctx
)
{
    return OP_ENOSYS;
}