//this file was generated by ../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__batchnormalization__9;

operator_set_opname opname_operator__ai_onnx__batchnormalization = {
    .name = "BatchNormalization",
    .opversions = {
        &opversion_operator__ai_onnx__batchnormalization__9,
        NULL
    }
};