//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__argmax__12.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__argmax__12(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_data);

    // Onnx__AttributeProto *a_axis = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"axis");
    // Onnx__AttributeProto *a_keepdims = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"keepdims");
    // Onnx__AttributeProto *a_select_last_index = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"select_last_index");

    // TRACE_ATTRIBUTE(2, a_axis, a_axis);
    // TRACE_ATTRIBUTE(2, a_keepdims, a_keepdims);
    // TRACE_ATTRIBUTE(2, a_select_last_index, a_select_last_index);

    // Onnx__TensorProto *o_reduced = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_reduced);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__argmax__12 *op_ctx = ctx->executer_context;

    // TRACE_VAR(2, true, op_ctx->axis, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->keepdims, "%" PRId64);
    // TRACE_VAR(2, true, op_ctx->select_last_index, "%" PRId64);

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_reduced);
    // free(o_reduced->dims);

    TRACE_EXIT(1);
}