//this file was generated by ../../../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operator__ai_onnx__argmax__12.h"

operator_set_opversion opversion_operator__ai_onnx__argmax__12 = {
    .version  = 12,
    .preparer = prepare_operator__ai_onnx__argmax__12,
    .info = &info_operator__ai_onnx__argmax__12
};